// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file clients/client_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActionRequest, ActionResponse, Empty, StatusUpdate } from "./client_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service woodhouse.api.v1.clients.ClientService
 */
export const ClientService = {
  typeName: "woodhouse.api.v1.clients.ClientService",
  methods: {
    /**
     * StatusStream allows the client to stream StatusUpdates to the server. The
     * first StatusUpdate should contain the full state of the client and any
     * subsequent update should only contain diffs - i.e. include the
     * client_info and all devices. See the Device type for what to include in a
     * full state update.
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.StatusStream
     */
    statusStream: {
      name: "StatusStream",
      I: StatusUpdate,
      O: Empty,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * ActionStream allows the client to receive ActionRequests from the server
     * (when they are created by users or automations). The client must
     * eventually respond to all ActionRequests by sending an ActionResponse
     * with the same ID and the current status of the action (this allows for
     * reactive user interfaces and automations to implement retries, etc).
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.ActionStream
     */
    actionStream: {
      name: "ActionStream",
      I: ActionResponse,
      O: ActionRequest,
      kind: MethodKind.BiDiStreaming,
    },
  }
};

