// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file clients/client_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActionRequest, ActionResponse, Empty, StatusUpdate } from "./client_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service woodhouse.api.v1.clients.ClientService
 */
export declare const ClientService: {
  readonly typeName: "woodhouse.api.v1.clients.ClientService",
  readonly methods: {
    /**
     * StatusStream allows the client to stream StatusUpdates to the server. The
     * first StatusUpdate should contain the whole state of the client and any
     * subsequent update should only contain diffs.
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.StatusStream
     */
    readonly statusStream: {
      readonly name: "StatusStream",
      readonly I: typeof StatusUpdate,
      readonly O: typeof Empty,
      readonly kind: MethodKind.ClientStreaming,
    },
    /**
     * ActionStream allows the client to receive ActionRequests from the server
     * (when they are created by users or automations). The client must
     * eventually respond to all ActionRequests by sending an ActionResponse
     * with the same ID and the current status of the action (this allows for
     * reactive user interfaces and automations to implement retries, etc).
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.ActionStream
     */
    readonly actionStream: {
      readonly name: "ActionStream",
      readonly I: typeof ActionResponse,
      readonly O: typeof ActionRequest,
      readonly kind: MethodKind.BiDiStreaming,
    },
  }
};

