// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file clients/user_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message woodhouse.api.v1.clients.GetDevicesRequest
 */
export declare class GetDevicesRequest extends Message<GetDevicesRequest> {
  constructor(data?: PartialMessage<GetDevicesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.GetDevicesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDevicesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDevicesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDevicesRequest;

  static equals(a: GetDevicesRequest | PlainMessage<GetDevicesRequest> | undefined, b: GetDevicesRequest | PlainMessage<GetDevicesRequest> | undefined): boolean;
}

/**
 * @generated from message woodhouse.api.v1.clients.DevicesStreamRequest
 */
export declare class DevicesStreamRequest extends Message<DevicesStreamRequest> {
  constructor(data?: PartialMessage<DevicesStreamRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.DevicesStreamRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DevicesStreamRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DevicesStreamRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DevicesStreamRequest;

  static equals(a: DevicesStreamRequest | PlainMessage<DevicesStreamRequest> | undefined, b: DevicesStreamRequest | PlainMessage<DevicesStreamRequest> | undefined): boolean;
}

