// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file clients/user_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message woodhouse.api.v1.clients.GetDevicesRequest
 */
export const GetDevicesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "woodhouse.api.v1.clients.GetDevicesRequest",
  [],
);

/**
 * @generated from message woodhouse.api.v1.clients.DevicesStreamRequest
 */
export const DevicesStreamRequest = /*@__PURE__*/ proto3.makeMessageType(
  "woodhouse.api.v1.clients.DevicesStreamRequest",
  () => [
    { no: 1, name: "include_device_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

