// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file clients/user_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DevicesStreamRequest, GetDevicesRequest } from "./user_service_pb.js";
import { ActionRequest, ActionResponse, Device } from "./client_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service woodhouse.api.v1.clients.UserService
 */
export const UserService = {
  typeName: "woodhouse.api.v1.clients.UserService",
  methods: {
    /**
     * @generated from rpc woodhouse.api.v1.clients.UserService.GetDevices
     */
    getDevices: {
      name: "GetDevices",
      I: GetDevicesRequest,
      O: Device,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc woodhouse.api.v1.clients.UserService.DevicesStream
     */
    devicesStream: {
      name: "DevicesStream",
      I: DevicesStreamRequest,
      O: Device,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc woodhouse.api.v1.clients.UserService.SendAction
     */
    sendAction: {
      name: "SendAction",
      I: ActionRequest,
      O: ActionResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
};

