version: '3'

tasks:
  default:
    deps:
      - proto

  proto:
    run: when_changed
    sources:
      - ../api/v1/*/*.proto
    generates:
      - ./src/api/v1/*/*.pb.go
    vars:
      PROTOC_GEN_ES: node_modules/.bin/protoc-gen-es{{exeExt}}
      PROTOC_GEN_CONNECT_ES: node_modules/.bin/protoc-gen-connect-es{{exeExt}}
    cmds:
      - mkdir -p ./src/lib/api/v1
      - protoc -I../api/v1
        --plugin="protoc-gen-es={{.PROTOC_GEN_ES}}"
        --plugin="protoc-gen-connect-es={{.PROTOC_GEN_CONNECT_ES}}"
        --es_out ./src/lib/api/v1
        --es_opt target=js+dts
        --connect-es_out ./src/lib/api/v1
        --connect-es_opt target=js+dts
        ../api/v1/*/*.proto

  build:
    deps:
      - proto
    cmds:
      - npm run build

  dev:
    deps:
      - proto
    cmds:
      - npm run dev
