// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: clients/client_service.proto

package clientsapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	// StatusStream allows the client to stream StatusUpdates to the server. The
	// first StatusUpdate should contain the full state of the client and any
	// subsequent update should only contain diffs - i.e. include the
	// client_info and all devices. See the Device type for what to include in a
	// full state update.
	StatusStream(ctx context.Context, opts ...grpc.CallOption) (ClientService_StatusStreamClient, error)
	// ActionStream allows the client to receive ActionRequests from the server
	// (when they are created by users or automations). The client must
	// eventually respond to all ActionRequests by sending an ActionResponse
	// with the same ID and the current status of the action (this allows for
	// reactive user interfaces and automations to implement retries, etc).
	ActionStream(ctx context.Context, opts ...grpc.CallOption) (ClientService_ActionStreamClient, error)
	ImageStream(ctx context.Context, opts ...grpc.CallOption) (ClientService_ImageStreamClient, error)
	// Get a stream of Device updates. The first batch of replies will be the
	// current state of the devices, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty Device) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	DeviceStream(ctx context.Context, opts ...grpc.CallOption) (ClientService_DeviceStreamClient, error)
	// Send an action to a device service.
	SendAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (ClientService_SendActionClient, error)
	// Send an image request to a device service.
	SendImageRequest(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (ClientService_SendImageRequestClient, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) StatusStream(ctx context.Context, opts ...grpc.CallOption) (ClientService_StatusStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[0], "/woodhouse.api.v1.clients.ClientService/StatusStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientServiceStatusStreamClient{stream}
	return x, nil
}

type ClientService_StatusStreamClient interface {
	Send(*StatusUpdate) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type clientServiceStatusStreamClient struct {
	grpc.ClientStream
}

func (x *clientServiceStatusStreamClient) Send(m *StatusUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientServiceStatusStreamClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientServiceClient) ActionStream(ctx context.Context, opts ...grpc.CallOption) (ClientService_ActionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[1], "/woodhouse.api.v1.clients.ClientService/ActionStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientServiceActionStreamClient{stream}
	return x, nil
}

type ClientService_ActionStreamClient interface {
	Send(*ActionResponse) error
	Recv() (*ActionRequest, error)
	grpc.ClientStream
}

type clientServiceActionStreamClient struct {
	grpc.ClientStream
}

func (x *clientServiceActionStreamClient) Send(m *ActionResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientServiceActionStreamClient) Recv() (*ActionRequest, error) {
	m := new(ActionRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientServiceClient) ImageStream(ctx context.Context, opts ...grpc.CallOption) (ClientService_ImageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[2], "/woodhouse.api.v1.clients.ClientService/ImageStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientServiceImageStreamClient{stream}
	return x, nil
}

type ClientService_ImageStreamClient interface {
	Send(*ImageResponse) error
	Recv() (*ImageRequest, error)
	grpc.ClientStream
}

type clientServiceImageStreamClient struct {
	grpc.ClientStream
}

func (x *clientServiceImageStreamClient) Send(m *ImageResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientServiceImageStreamClient) Recv() (*ImageRequest, error) {
	m := new(ImageRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientServiceClient) DeviceStream(ctx context.Context, opts ...grpc.CallOption) (ClientService_DeviceStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[3], "/woodhouse.api.v1.clients.ClientService/DeviceStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientServiceDeviceStreamClient{stream}
	return x, nil
}

type ClientService_DeviceStreamClient interface {
	Send(*DeviceStreamRequest) error
	Recv() (*Device, error)
	grpc.ClientStream
}

type clientServiceDeviceStreamClient struct {
	grpc.ClientStream
}

func (x *clientServiceDeviceStreamClient) Send(m *DeviceStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientServiceDeviceStreamClient) Recv() (*Device, error) {
	m := new(Device)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientServiceClient) SendAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (ClientService_SendActionClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[4], "/woodhouse.api.v1.clients.ClientService/SendAction", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientServiceSendActionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ClientService_SendActionClient interface {
	Recv() (*ActionResponse, error)
	grpc.ClientStream
}

type clientServiceSendActionClient struct {
	grpc.ClientStream
}

func (x *clientServiceSendActionClient) Recv() (*ActionResponse, error) {
	m := new(ActionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientServiceClient) SendImageRequest(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (ClientService_SendImageRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientService_ServiceDesc.Streams[5], "/woodhouse.api.v1.clients.ClientService/SendImageRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientServiceSendImageRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ClientService_SendImageRequestClient interface {
	Recv() (*ImageResponse, error)
	grpc.ClientStream
}

type clientServiceSendImageRequestClient struct {
	grpc.ClientStream
}

func (x *clientServiceSendImageRequestClient) Recv() (*ImageResponse, error) {
	m := new(ImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility
type ClientServiceServer interface {
	// StatusStream allows the client to stream StatusUpdates to the server. The
	// first StatusUpdate should contain the full state of the client and any
	// subsequent update should only contain diffs - i.e. include the
	// client_info and all devices. See the Device type for what to include in a
	// full state update.
	StatusStream(ClientService_StatusStreamServer) error
	// ActionStream allows the client to receive ActionRequests from the server
	// (when they are created by users or automations). The client must
	// eventually respond to all ActionRequests by sending an ActionResponse
	// with the same ID and the current status of the action (this allows for
	// reactive user interfaces and automations to implement retries, etc).
	ActionStream(ClientService_ActionStreamServer) error
	ImageStream(ClientService_ImageStreamServer) error
	// Get a stream of Device updates. The first batch of replies will be the
	// current state of the devices, followed by updates when they occur. The
	// stream also includes a 10 second heartbeat (an empty Device) which should
	// be ignored, but can be used to monitor the stream for disconnects.
	DeviceStream(ClientService_DeviceStreamServer) error
	// Send an action to a device service.
	SendAction(*ActionRequest, ClientService_SendActionServer) error
	// Send an image request to a device service.
	SendImageRequest(*ImageRequest, ClientService_SendImageRequestServer) error
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (UnimplementedClientServiceServer) StatusStream(ClientService_StatusStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method StatusStream not implemented")
}
func (UnimplementedClientServiceServer) ActionStream(ClientService_ActionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ActionStream not implemented")
}
func (UnimplementedClientServiceServer) ImageStream(ClientService_ImageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ImageStream not implemented")
}
func (UnimplementedClientServiceServer) DeviceStream(ClientService_DeviceStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DeviceStream not implemented")
}
func (UnimplementedClientServiceServer) SendAction(*ActionRequest, ClientService_SendActionServer) error {
	return status.Errorf(codes.Unimplemented, "method SendAction not implemented")
}
func (UnimplementedClientServiceServer) SendImageRequest(*ImageRequest, ClientService_SendImageRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method SendImageRequest not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_StatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).StatusStream(&clientServiceStatusStreamServer{stream})
}

type ClientService_StatusStreamServer interface {
	SendAndClose(*Empty) error
	Recv() (*StatusUpdate, error)
	grpc.ServerStream
}

type clientServiceStatusStreamServer struct {
	grpc.ServerStream
}

func (x *clientServiceStatusStreamServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientServiceStatusStreamServer) Recv() (*StatusUpdate, error) {
	m := new(StatusUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ClientService_ActionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).ActionStream(&clientServiceActionStreamServer{stream})
}

type ClientService_ActionStreamServer interface {
	Send(*ActionRequest) error
	Recv() (*ActionResponse, error)
	grpc.ServerStream
}

type clientServiceActionStreamServer struct {
	grpc.ServerStream
}

func (x *clientServiceActionStreamServer) Send(m *ActionRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientServiceActionStreamServer) Recv() (*ActionResponse, error) {
	m := new(ActionResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ClientService_ImageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).ImageStream(&clientServiceImageStreamServer{stream})
}

type ClientService_ImageStreamServer interface {
	Send(*ImageRequest) error
	Recv() (*ImageResponse, error)
	grpc.ServerStream
}

type clientServiceImageStreamServer struct {
	grpc.ServerStream
}

func (x *clientServiceImageStreamServer) Send(m *ImageRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientServiceImageStreamServer) Recv() (*ImageResponse, error) {
	m := new(ImageResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ClientService_DeviceStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).DeviceStream(&clientServiceDeviceStreamServer{stream})
}

type ClientService_DeviceStreamServer interface {
	Send(*Device) error
	Recv() (*DeviceStreamRequest, error)
	grpc.ServerStream
}

type clientServiceDeviceStreamServer struct {
	grpc.ServerStream
}

func (x *clientServiceDeviceStreamServer) Send(m *Device) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientServiceDeviceStreamServer) Recv() (*DeviceStreamRequest, error) {
	m := new(DeviceStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ClientService_SendAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientServiceServer).SendAction(m, &clientServiceSendActionServer{stream})
}

type ClientService_SendActionServer interface {
	Send(*ActionResponse) error
	grpc.ServerStream
}

type clientServiceSendActionServer struct {
	grpc.ServerStream
}

func (x *clientServiceSendActionServer) Send(m *ActionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ClientService_SendImageRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientServiceServer).SendImageRequest(m, &clientServiceSendImageRequestServer{stream})
}

type ClientService_SendImageRequestServer interface {
	Send(*ImageResponse) error
	grpc.ServerStream
}

type clientServiceSendImageRequestServer struct {
	grpc.ServerStream
}

func (x *clientServiceSendImageRequestServer) Send(m *ImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woodhouse.api.v1.clients.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusStream",
			Handler:       _ClientService_StatusStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ActionStream",
			Handler:       _ClientService_ActionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ImageStream",
			Handler:       _ClientService_ImageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DeviceStream",
			Handler:       _ClientService_DeviceStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendAction",
			Handler:       _ClientService_SendAction_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendImageRequest",
			Handler:       _ClientService_SendImageRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clients/client_service.proto",
}
