// source: bridge.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var timestamp_pb = require('./timestamp_pb.js');
goog.object.extend(proto, timestamp_pb);
goog.exportSymbol('proto.woodhouse.api.BridgeInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.woodhouse.api.BridgeInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.woodhouse.api.BridgeInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.woodhouse.api.BridgeInfo.displayName = 'proto.woodhouse.api.BridgeInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.woodhouse.api.BridgeInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.woodhouse.api.BridgeInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.woodhouse.api.BridgeInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.woodhouse.api.BridgeInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    bridgeId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    bootTime: (f = msg.getBootTime()) && timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.woodhouse.api.BridgeInfo}
 */
proto.woodhouse.api.BridgeInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.woodhouse.api.BridgeInfo;
  return proto.woodhouse.api.BridgeInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.woodhouse.api.BridgeInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.woodhouse.api.BridgeInfo}
 */
proto.woodhouse.api.BridgeInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBridgeId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = new timestamp_pb.Timestamp;
      reader.readMessage(value,timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setBootTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.woodhouse.api.BridgeInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.woodhouse.api.BridgeInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.woodhouse.api.BridgeInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.woodhouse.api.BridgeInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBridgeId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBootTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string bridge_id = 1;
 * @return {string}
 */
proto.woodhouse.api.BridgeInfo.prototype.getBridgeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.woodhouse.api.BridgeInfo} returns this
 */
proto.woodhouse.api.BridgeInfo.prototype.setBridgeId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.woodhouse.api.BridgeInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.woodhouse.api.BridgeInfo} returns this
 */
proto.woodhouse.api.BridgeInfo.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.woodhouse.api.BridgeInfo.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.woodhouse.api.BridgeInfo} returns this
 */
proto.woodhouse.api.BridgeInfo.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Timestamp boot_time = 4;
 * @return {?proto.woodhouse.api.Timestamp}
 */
proto.woodhouse.api.BridgeInfo.prototype.getBootTime = function() {
  return /** @type{?proto.woodhouse.api.Timestamp} */ (
    jspb.Message.getWrapperField(this, timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.woodhouse.api.Timestamp|undefined} value
 * @return {!proto.woodhouse.api.BridgeInfo} returns this
*/
proto.woodhouse.api.BridgeInfo.prototype.setBootTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.woodhouse.api.BridgeInfo} returns this
 */
proto.woodhouse.api.BridgeInfo.prototype.clearBootTime = function() {
  return this.setBootTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.woodhouse.api.BridgeInfo.prototype.hasBootTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.woodhouse.api);
