// source: device_store.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var bridge_pb = require('./bridge_pb.js');
goog.object.extend(proto, bridge_pb);
var device_pb = require('./device_pb.js');
goog.object.extend(proto, device_pb);
goog.exportSymbol('proto.woodhouse.api.DeviceStore', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.woodhouse.api.DeviceStore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.woodhouse.api.DeviceStore.repeatedFields_, null);
};
goog.inherits(proto.woodhouse.api.DeviceStore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.woodhouse.api.DeviceStore.displayName = 'proto.woodhouse.api.DeviceStore';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.woodhouse.api.DeviceStore.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.woodhouse.api.DeviceStore.prototype.toObject = function(opt_includeInstance) {
  return proto.woodhouse.api.DeviceStore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.woodhouse.api.DeviceStore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.woodhouse.api.DeviceStore.toObject = function(includeInstance, msg) {
  var f, obj = {
    bridgeInfosList: jspb.Message.toObjectList(msg.getBridgeInfosList(),
    bridge_pb.BridgeInfo.toObject, includeInstance),
    deviceInfosList: jspb.Message.toObjectList(msg.getDeviceInfosList(),
    device_pb.DeviceExtendedInfo.toObject, includeInstance),
    deviceStatesList: jspb.Message.toObjectList(msg.getDeviceStatesList(),
    device_pb.DeviceState.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.woodhouse.api.DeviceStore}
 */
proto.woodhouse.api.DeviceStore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.woodhouse.api.DeviceStore;
  return proto.woodhouse.api.DeviceStore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.woodhouse.api.DeviceStore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.woodhouse.api.DeviceStore}
 */
proto.woodhouse.api.DeviceStore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bridge_pb.BridgeInfo;
      reader.readMessage(value,bridge_pb.BridgeInfo.deserializeBinaryFromReader);
      msg.addBridgeInfos(value);
      break;
    case 2:
      var value = new device_pb.DeviceExtendedInfo;
      reader.readMessage(value,device_pb.DeviceExtendedInfo.deserializeBinaryFromReader);
      msg.addDeviceInfos(value);
      break;
    case 3:
      var value = new device_pb.DeviceState;
      reader.readMessage(value,device_pb.DeviceState.deserializeBinaryFromReader);
      msg.addDeviceStates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.woodhouse.api.DeviceStore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.woodhouse.api.DeviceStore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.woodhouse.api.DeviceStore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.woodhouse.api.DeviceStore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBridgeInfosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      bridge_pb.BridgeInfo.serializeBinaryToWriter
    );
  }
  f = message.getDeviceInfosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      device_pb.DeviceExtendedInfo.serializeBinaryToWriter
    );
  }
  f = message.getDeviceStatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      device_pb.DeviceState.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BridgeInfo bridge_infos = 1;
 * @return {!Array<!proto.woodhouse.api.BridgeInfo>}
 */
proto.woodhouse.api.DeviceStore.prototype.getBridgeInfosList = function() {
  return /** @type{!Array<!proto.woodhouse.api.BridgeInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, bridge_pb.BridgeInfo, 1));
};


/**
 * @param {!Array<!proto.woodhouse.api.BridgeInfo>} value
 * @return {!proto.woodhouse.api.DeviceStore} returns this
*/
proto.woodhouse.api.DeviceStore.prototype.setBridgeInfosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.woodhouse.api.BridgeInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.woodhouse.api.BridgeInfo}
 */
proto.woodhouse.api.DeviceStore.prototype.addBridgeInfos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.woodhouse.api.BridgeInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.woodhouse.api.DeviceStore} returns this
 */
proto.woodhouse.api.DeviceStore.prototype.clearBridgeInfosList = function() {
  return this.setBridgeInfosList([]);
};


/**
 * repeated DeviceExtendedInfo device_infos = 2;
 * @return {!Array<!proto.woodhouse.api.DeviceExtendedInfo>}
 */
proto.woodhouse.api.DeviceStore.prototype.getDeviceInfosList = function() {
  return /** @type{!Array<!proto.woodhouse.api.DeviceExtendedInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, device_pb.DeviceExtendedInfo, 2));
};


/**
 * @param {!Array<!proto.woodhouse.api.DeviceExtendedInfo>} value
 * @return {!proto.woodhouse.api.DeviceStore} returns this
*/
proto.woodhouse.api.DeviceStore.prototype.setDeviceInfosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.woodhouse.api.DeviceExtendedInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.woodhouse.api.DeviceExtendedInfo}
 */
proto.woodhouse.api.DeviceStore.prototype.addDeviceInfos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.woodhouse.api.DeviceExtendedInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.woodhouse.api.DeviceStore} returns this
 */
proto.woodhouse.api.DeviceStore.prototype.clearDeviceInfosList = function() {
  return this.setDeviceInfosList([]);
};


/**
 * repeated DeviceState device_states = 3;
 * @return {!Array<!proto.woodhouse.api.DeviceState>}
 */
proto.woodhouse.api.DeviceStore.prototype.getDeviceStatesList = function() {
  return /** @type{!Array<!proto.woodhouse.api.DeviceState>} */ (
    jspb.Message.getRepeatedWrapperField(this, device_pb.DeviceState, 3));
};


/**
 * @param {!Array<!proto.woodhouse.api.DeviceState>} value
 * @return {!proto.woodhouse.api.DeviceStore} returns this
*/
proto.woodhouse.api.DeviceStore.prototype.setDeviceStatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.woodhouse.api.DeviceState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.woodhouse.api.DeviceState}
 */
proto.woodhouse.api.DeviceStore.prototype.addDeviceStates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.woodhouse.api.DeviceState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.woodhouse.api.DeviceStore} returns this
 */
proto.woodhouse.api.DeviceStore.prototype.clearDeviceStatesList = function() {
  return this.setDeviceStatesList([]);
};


goog.object.extend(exports, proto.woodhouse.api);
