version: '3'

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

tasks:
  default:
    deps:
      - build

  proto:
    deps:
      - api:proto-go

  build:
    deps:
      - build-core
      - build-bridge-shelly
      - build-bridge-zigbee

  run:
    deps:
      - run-core

  build-core:
    deps:
      - proto
    cmds:
      - mkdir -p build
      - go build -o build/woodhouse-core{{exeExt}} ./cmd/woodhouse-core

  run-core:
    deps:
      - build-core
    cmds:
      - cd build && ./woodhouse-core{{exeExt}} {{.CLI_ARGS}}

  build-bridge-shelly:
    deps:
      - proto
    cmds:
      - mkdir -p build
      - go build -o build/woodhouse-bridge-shelly{{exeExt}} ./cmd/woodhouse-bridge-shelly

  run-bridge-shelly:
    deps:
      - build-bridge-shelly
    cmds:
      - cd build && ./woodhouse-bridge-shelly{{exeExt}} {{.CLI_ARGS}}

  build-bridge-zigbee:
    deps:
      - proto
    cmds:
      - mkdir -p build
      - go build -o build/woodhouse-bridge-zigbee{{exeExt}} ./cmd/woodhouse-bridge-zigbee

  run-bridge-zigbee:
    deps:
      - build-bridge-zigbee
    cmds:
      - cd build && ./woodhouse-bridge-zigbee{{exeExt}} {{.CLI_ARGS}}
