version: '3'

vars:
  GOOS:
    sh: go env GOOS
  GOARCH:
    sh: go env GOARCH
  BUILD_DIR: "build-{{.GOOS}}-{{.GOARCH}}"

dotenv:
  - '.env'

includes:
  api:
    taskfile: ./api
    dir: ./api

tasks:
  build-api:
    desc: Generate API code from protos
    cmds:
      - task api:proto-go-v1

  generate-env:
    desc: Generate the default .env file
    status:
      - test -f .env
    cmds:
      - cp dot-env .env

  build-core:
    desc: Build woodhouse-core
    cmds:
      - task: build-api
      # - task: webapp:build
      - task: build-component
        vars: { GOOS: "{{.GOOS}}", GOARCH: "{{.GOARCH}}", COMPONENT: "woodhouse-core" }

  deploy-core:
    desc: Deploy woodhouse-core to your confiugred system (use 'generate-env' to configure)
    cmds:
      - task: build-api
      # - task: webapp:build
      - task: build-and-deploy-component
        vars: { GOOS: "{{.DEPLOY_GOOS}}", GOARCH: "{{.DEPLOY_GOARCH}}", COMPONENT: "woodhouse-core" }

  # run-core:
  #   deps:
  #     - build-core
  #   cmds:
  #     - cd {{.BUILD_DIR}} && ./woodhouse-core{{exeExt}} {{.CLI_ARGS}}

  # build-frigate:
  #   cmds:
  #     - go build -o {{.BUILD_DIR}}/woodhouse-frigate{{exeExt}} ./cmd/woodhouse-frigate

  # run-frigate:
  #   deps:
  #     - build-frigate
  #   cmds:
  #     - cd {{.BUILD_DIR}} && ./woodhouse-frigate{{exeExt}} {{.CLI_ARGS}}

  # build-whctl:
  #   cmds:
  #     - go build -o {{.BUILD_DIR}}/whctl{{exeExt}} ./cmd/whctl

  # run-whctl:
  #   deps:
  #     - build-whctl
  #   cmds:
  #     - cd {{.BUILD_DIR}} && ./whctl{{exeExt}} {{.CLI_ARGS}}

  # build-client:
  #   cmds:
  #     - go build -o {{.BUILD_DIR}}/woodhouse-client{{exeExt}} ./cmd/woodhouse-client

  # run-client:
  #   deps:
  #     - build-client
  #   cmds:
  #     - cd {{.BUILD_DIR}} && ./woodhouse-client{{exeExt}} {{.CLI_ARGS}}

  # build-reactor:
  #   cmds:
  #     - go build -o {{.BUILD_DIR}}/woodhouse-reactor{{exeExt}} ./cmd/woodhouse-reactor

  # run-reactor:
  #   deps:
  #     - build-reactor
  #   cmds:
  #     - cd {{.BUILD_DIR}} && ./woodhouse-reactor{{exeExt}} {{.CLI_ARGS}}

  # build-shelly:
  #   cmds:
  #     - go build -o {{.BUILD_DIR}}/woodhouse-shelly{{exeExt}} ./cmd/woodhouse-shelly

  # run-shelly:
  #   deps:
  #     - build-shelly
  #   cmds:
  #     - cd {{.BUILD_DIR}} && ./woodhouse-shelly{{exeExt}} {{.CLI_ARGS}}

  # build-tasmota:
  #   cmds:
  #     - go build -o {{.BUILD_DIR}}/woodhouse-tasmota{{exeExt}} ./cmd/woodhouse-tasmota

  # run-tasmota:
  #   deps:
  #     - build-tasmota
  #   cmds:
  #     - cd {{.BUILD_DIR}} && ./woodhouse-tasmota{{exeExt}} {{.CLI_ARGS}}

  # build-zigbee:
  #   cmds:
  #     - go build -o {{.BUILD_DIR}}/woodhouse-zigbee{{exeExt}} ./cmd/woodhouse-zigbee

  # run-zigbee:
  #   deps:
  #     - build-zigbee
  #   cmds:
  #     - cd {{.BUILD_DIR}} && ./woodhouse-zigbee{{exeExt}} {{.CLI_ARGS}}

  build-zigbee:
    cmds:
      - task: build-component
        vars: { GOOS: "{{.GOOS}}", GOARCH: "{{.GOARCH}}", COMPONENT: "woodhouse-zigbee" }

  deploy-zigbee:
    cmds:
      - task: build-and-deploy-component
        vars: { GOOS: "{{.DEPLOY_GOOS}}", GOARCH: "{{.DEPLOY_GOARCH}}", COMPONENT: "woodhouse-zigbee" }

  build-component:
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
    vars:
      BUILD_DIR: "build-{{.GOOS}}-{{.GOARCH}}"
    requires:
      vars: [COMPONENT]
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.COMPONENT}}{{exeExt}} ./cmd/{{.COMPONENT}}

  build-and-deploy-component:
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
    vars:
      BUILD_DIR: "build-{{.GOOS}}-{{.GOARCH}}"
    requires:
      vars: [COMPONENT]
    cmds:
      - test "$DEPLOY_HOST"
      - test "$DEPLOY_USER"
      - test "$DEPLOY_DIR"
      - test "$DEPLOY_GOOS"
      - test "$DEPLOY_GOARCH"
      - go build -o {{.BUILD_DIR}}/{{.COMPONENT}}{{exeExt}} ./cmd/{{.COMPONENT}}
      - rsync {{.BUILD_DIR}}/{{.COMPONENT}}{{exeExt}} $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR/{{.BUILD_DIR}}/
      - ssh $DEPLOY_USER@$DEPLOY_HOST systemctl --user restart {{.COMPONENT}}.service
