version: '3'

vars:
  GOOS:
    sh: go env GOOS
  GOARCH:
    sh: go env GOARCH
  BUILD_DIR: "build-{{.GOOS}}-{{.GOARCH}}"

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api
  webapp:
    taskfile: ./webapp/Taskfile.yaml
    dir: ./webapp

tasks:
  default:
    deps:
      - build

  proto:
    deps:
      - api:proto-go
      - api:proto-go-v1

  proto-all:
    deps:
      - proto
      - webapp:proto

  build-dir:
    cmds:
      - mkdir -p "{{.BUILD_DIR}}"

  build-all:
    deps:
      - proto
      - build-dir
      - webapp:proto
      - webapp:proto
    cmds:
      - task: build-web
      - task: build
  build:
    deps:
      - build-core
      - build-shelly
      - build-zigbee

  run:
    deps:
      - run-core

  build-web:
    cmds:
      - task: webapp:build

  build-core:
    cmds:
      - go build -o {{.BUILD_DIR}}/woodhouse-core{{exeExt}} ./cmd/woodhouse-core

  run-core:
    deps:
      - build-core
    cmds:
      - cd {{.BUILD_DIR}} && ./woodhouse-core{{exeExt}} {{.CLI_ARGS}}

  build-frigate:
    cmds:
      - go build -o {{.BUILD_DIR}}/woodhouse-frigate{{exeExt}} ./cmd/woodhouse-frigate

  run-frigate:
    deps:
      - build-frigate
    cmds:
      - cd {{.BUILD_DIR}} && ./woodhouse-frigate{{exeExt}} {{.CLI_ARGS}}

  build-whctl:
    cmds:
      - go build -o {{.BUILD_DIR}}/whctl{{exeExt}} ./cmd/whctl

  run-whctl:
    deps:
      - build-whctl
    cmds:
      - cd {{.BUILD_DIR}} && ./whctl{{exeExt}} {{.CLI_ARGS}}

  build-client:
    cmds:
      - go build -o {{.BUILD_DIR}}/woodhouse-client{{exeExt}} ./cmd/woodhouse-client

  run-client:
    deps:
      - build-client
    cmds:
      - cd {{.BUILD_DIR}} && ./woodhouse-client{{exeExt}} {{.CLI_ARGS}}

  build-reactor:
    cmds:
      - go build -o {{.BUILD_DIR}}/woodhouse-reactor{{exeExt}} ./cmd/woodhouse-reactor

  run-reactor:
    deps:
      - build-reactor
    cmds:
      - cd {{.BUILD_DIR}} && ./woodhouse-reactor{{exeExt}} {{.CLI_ARGS}}

  build-shelly:
    cmds:
      - go build -o {{.BUILD_DIR}}/woodhouse-shelly{{exeExt}} ./cmd/woodhouse-shelly

  run-shelly:
    deps:
      - build-shelly
    cmds:
      - cd {{.BUILD_DIR}} && ./woodhouse-shelly{{exeExt}} {{.CLI_ARGS}}

  build-zigbee:
    cmds:
      - go build -o {{.BUILD_DIR}}/woodhouse-zigbee{{exeExt}} ./cmd/woodhouse-zigbee

  run-zigbee:
    deps:
      - build-zigbee
    cmds:
      - cd {{.BUILD_DIR}} && ./woodhouse-zigbee{{exeExt}} {{.CLI_ARGS}}
