// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: bridge_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BridgeServiceClient is the client API for BridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeServiceClient interface {
	SetBridgeInfo(ctx context.Context, in *BridgeInfo, opts ...grpc.CallOption) (*SetBridgeInfoResponse, error)
	SetDeviceInfo(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*SetDeviceInfoResponse, error)
	SetDeviceState(ctx context.Context, in *DeviceState, opts ...grpc.CallOption) (*SetDeviceStateResponse, error)
	GetDeviceRequests(ctx context.Context, opts ...grpc.CallOption) (BridgeService_GetDeviceRequestsClient, error)
}

type bridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeServiceClient(cc grpc.ClientConnInterface) BridgeServiceClient {
	return &bridgeServiceClient{cc}
}

func (c *bridgeServiceClient) SetBridgeInfo(ctx context.Context, in *BridgeInfo, opts ...grpc.CallOption) (*SetBridgeInfoResponse, error) {
	out := new(SetBridgeInfoResponse)
	err := c.cc.Invoke(ctx, "/woodhouse.api.BridgeService/SetBridgeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetDeviceInfo(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*SetDeviceInfoResponse, error) {
	out := new(SetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, "/woodhouse.api.BridgeService/SetDeviceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetDeviceState(ctx context.Context, in *DeviceState, opts ...grpc.CallOption) (*SetDeviceStateResponse, error) {
	out := new(SetDeviceStateResponse)
	err := c.cc.Invoke(ctx, "/woodhouse.api.BridgeService/SetDeviceState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) GetDeviceRequests(ctx context.Context, opts ...grpc.CallOption) (BridgeService_GetDeviceRequestsClient, error) {
	stream, err := c.cc.NewStream(ctx, &BridgeService_ServiceDesc.Streams[0], "/woodhouse.api.BridgeService/GetDeviceRequests", opts...)
	if err != nil {
		return nil, err
	}
	x := &bridgeServiceGetDeviceRequestsClient{stream}
	return x, nil
}

type BridgeService_GetDeviceRequestsClient interface {
	Send(*DeviceResponse) error
	Recv() (*DeviceRequest, error)
	grpc.ClientStream
}

type bridgeServiceGetDeviceRequestsClient struct {
	grpc.ClientStream
}

func (x *bridgeServiceGetDeviceRequestsClient) Send(m *DeviceResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bridgeServiceGetDeviceRequestsClient) Recv() (*DeviceRequest, error) {
	m := new(DeviceRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BridgeServiceServer is the server API for BridgeService service.
// All implementations must embed UnimplementedBridgeServiceServer
// for forward compatibility
type BridgeServiceServer interface {
	SetBridgeInfo(context.Context, *BridgeInfo) (*SetBridgeInfoResponse, error)
	SetDeviceInfo(context.Context, *DeviceInfo) (*SetDeviceInfoResponse, error)
	SetDeviceState(context.Context, *DeviceState) (*SetDeviceStateResponse, error)
	GetDeviceRequests(BridgeService_GetDeviceRequestsServer) error
	mustEmbedUnimplementedBridgeServiceServer()
}

// UnimplementedBridgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBridgeServiceServer struct {
}

func (UnimplementedBridgeServiceServer) SetBridgeInfo(context.Context, *BridgeInfo) (*SetBridgeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBridgeInfo not implemented")
}
func (UnimplementedBridgeServiceServer) SetDeviceInfo(context.Context, *DeviceInfo) (*SetDeviceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceInfo not implemented")
}
func (UnimplementedBridgeServiceServer) SetDeviceState(context.Context, *DeviceState) (*SetDeviceStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceState not implemented")
}
func (UnimplementedBridgeServiceServer) GetDeviceRequests(BridgeService_GetDeviceRequestsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDeviceRequests not implemented")
}
func (UnimplementedBridgeServiceServer) mustEmbedUnimplementedBridgeServiceServer() {}

// UnsafeBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServiceServer will
// result in compilation errors.
type UnsafeBridgeServiceServer interface {
	mustEmbedUnimplementedBridgeServiceServer()
}

func RegisterBridgeServiceServer(s grpc.ServiceRegistrar, srv BridgeServiceServer) {
	s.RegisterService(&BridgeService_ServiceDesc, srv)
}

func _BridgeService_SetBridgeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetBridgeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/woodhouse.api.BridgeService/SetBridgeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetBridgeInfo(ctx, req.(*BridgeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/woodhouse.api.BridgeService/SetDeviceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetDeviceInfo(ctx, req.(*DeviceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/woodhouse.api.BridgeService/SetDeviceState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetDeviceState(ctx, req.(*DeviceState))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_GetDeviceRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BridgeServiceServer).GetDeviceRequests(&bridgeServiceGetDeviceRequestsServer{stream})
}

type BridgeService_GetDeviceRequestsServer interface {
	Send(*DeviceRequest) error
	Recv() (*DeviceResponse, error)
	grpc.ServerStream
}

type bridgeServiceGetDeviceRequestsServer struct {
	grpc.ServerStream
}

func (x *bridgeServiceGetDeviceRequestsServer) Send(m *DeviceRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bridgeServiceGetDeviceRequestsServer) Recv() (*DeviceResponse, error) {
	m := new(DeviceResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BridgeService_ServiceDesc is the grpc.ServiceDesc for BridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woodhouse.api.BridgeService",
	HandlerType: (*BridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBridgeInfo",
			Handler:    _BridgeService_SetBridgeInfo_Handler,
		},
		{
			MethodName: "SetDeviceInfo",
			Handler:    _BridgeService_SetDeviceInfo_Handler,
		},
		{
			MethodName: "SetDeviceState",
			Handler:    _BridgeService_SetDeviceState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDeviceRequests",
			Handler:       _BridgeService_GetDeviceRequests_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bridge_service.proto",
}

// BridgeAuthServiceClient is the client API for BridgeAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeAuthServiceClient interface {
	// Pair with (login to) the woodhouse core server. Note that this RPC can
	// wait in the pending state for a long time, until a user approves/denies
	// the pairing request. The bi-directional stream is normally used in
	// 'insecure' mode (i.e. use 'insecure skip verify' TLS option) and follows
	// this pattern (note that the bridge is the client here):
	//  1. The client starts the bi-directional stream by sending its client_id.
	//  2. The server will send back the 'Pending' state every second until a
	//     user has either accepted or denied the pairing request.
	//  3. If the user accepts the pairing request, the server will send the
	//     first PAKE handshake blob.
	//  4. The client should read the handshake into their PAKE object and send
	//     back the second PAKE handshake blob.
	//  5. Server and client should now have the session key. The server tests
	//     this by sending some random data to client after encrypting with
	//     AES-256.
	//  6. The client should then decrypt the random bytes, reverse the order,
	//     encrypt using its session key and send it back to the server.
	//  7. If the server is happy it will send its own certificate file in PEM
	//     format which the client should save and use to verify future
	//     connections.
	//  8. The server will then generate a new refresh token (JWT) and send it to
	//     the client. The client should save this and use it to obtain new
	//     tokens using the `Refresh` RPC.
	//  9. Server and client should now both finish the RPC. The client should
	//     now call `Refresh` to obtain an access token which...
	Pair(ctx context.Context, opts ...grpc.CallOption) (BridgeAuthService_PairClient, error)
	// Refresh session auth tokens. Should be called regularly before tokens
	// expire.
	Refresh(ctx context.Context, in *BridgeRefreshRequest, opts ...grpc.CallOption) (*BridgeRefreshResponse, error)
	// Logout the session.
	Logout(ctx context.Context, in *BridgeLogoutRequest, opts ...grpc.CallOption) (*BridgeLogoutResponse, error)
}

type bridgeAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeAuthServiceClient(cc grpc.ClientConnInterface) BridgeAuthServiceClient {
	return &bridgeAuthServiceClient{cc}
}

func (c *bridgeAuthServiceClient) Pair(ctx context.Context, opts ...grpc.CallOption) (BridgeAuthService_PairClient, error) {
	stream, err := c.cc.NewStream(ctx, &BridgeAuthService_ServiceDesc.Streams[0], "/woodhouse.api.BridgeAuthService/Pair", opts...)
	if err != nil {
		return nil, err
	}
	x := &bridgeAuthServicePairClient{stream}
	return x, nil
}

type BridgeAuthService_PairClient interface {
	Send(*BridgePairRequest) error
	Recv() (*BridgePairResponse, error)
	grpc.ClientStream
}

type bridgeAuthServicePairClient struct {
	grpc.ClientStream
}

func (x *bridgeAuthServicePairClient) Send(m *BridgePairRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bridgeAuthServicePairClient) Recv() (*BridgePairResponse, error) {
	m := new(BridgePairResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bridgeAuthServiceClient) Refresh(ctx context.Context, in *BridgeRefreshRequest, opts ...grpc.CallOption) (*BridgeRefreshResponse, error) {
	out := new(BridgeRefreshResponse)
	err := c.cc.Invoke(ctx, "/woodhouse.api.BridgeAuthService/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeAuthServiceClient) Logout(ctx context.Context, in *BridgeLogoutRequest, opts ...grpc.CallOption) (*BridgeLogoutResponse, error) {
	out := new(BridgeLogoutResponse)
	err := c.cc.Invoke(ctx, "/woodhouse.api.BridgeAuthService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeAuthServiceServer is the server API for BridgeAuthService service.
// All implementations must embed UnimplementedBridgeAuthServiceServer
// for forward compatibility
type BridgeAuthServiceServer interface {
	// Pair with (login to) the woodhouse core server. Note that this RPC can
	// wait in the pending state for a long time, until a user approves/denies
	// the pairing request. The bi-directional stream is normally used in
	// 'insecure' mode (i.e. use 'insecure skip verify' TLS option) and follows
	// this pattern (note that the bridge is the client here):
	//  1. The client starts the bi-directional stream by sending its client_id.
	//  2. The server will send back the 'Pending' state every second until a
	//     user has either accepted or denied the pairing request.
	//  3. If the user accepts the pairing request, the server will send the
	//     first PAKE handshake blob.
	//  4. The client should read the handshake into their PAKE object and send
	//     back the second PAKE handshake blob.
	//  5. Server and client should now have the session key. The server tests
	//     this by sending some random data to client after encrypting with
	//     AES-256.
	//  6. The client should then decrypt the random bytes, reverse the order,
	//     encrypt using its session key and send it back to the server.
	//  7. If the server is happy it will send its own certificate file in PEM
	//     format which the client should save and use to verify future
	//     connections.
	//  8. The server will then generate a new refresh token (JWT) and send it to
	//     the client. The client should save this and use it to obtain new
	//     tokens using the `Refresh` RPC.
	//  9. Server and client should now both finish the RPC. The client should
	//     now call `Refresh` to obtain an access token which...
	Pair(BridgeAuthService_PairServer) error
	// Refresh session auth tokens. Should be called regularly before tokens
	// expire.
	Refresh(context.Context, *BridgeRefreshRequest) (*BridgeRefreshResponse, error)
	// Logout the session.
	Logout(context.Context, *BridgeLogoutRequest) (*BridgeLogoutResponse, error)
	mustEmbedUnimplementedBridgeAuthServiceServer()
}

// UnimplementedBridgeAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBridgeAuthServiceServer struct {
}

func (UnimplementedBridgeAuthServiceServer) Pair(BridgeAuthService_PairServer) error {
	return status.Errorf(codes.Unimplemented, "method Pair not implemented")
}
func (UnimplementedBridgeAuthServiceServer) Refresh(context.Context, *BridgeRefreshRequest) (*BridgeRefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedBridgeAuthServiceServer) Logout(context.Context, *BridgeLogoutRequest) (*BridgeLogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedBridgeAuthServiceServer) mustEmbedUnimplementedBridgeAuthServiceServer() {}

// UnsafeBridgeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeAuthServiceServer will
// result in compilation errors.
type UnsafeBridgeAuthServiceServer interface {
	mustEmbedUnimplementedBridgeAuthServiceServer()
}

func RegisterBridgeAuthServiceServer(s grpc.ServiceRegistrar, srv BridgeAuthServiceServer) {
	s.RegisterService(&BridgeAuthService_ServiceDesc, srv)
}

func _BridgeAuthService_Pair_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BridgeAuthServiceServer).Pair(&bridgeAuthServicePairServer{stream})
}

type BridgeAuthService_PairServer interface {
	Send(*BridgePairResponse) error
	Recv() (*BridgePairRequest, error)
	grpc.ServerStream
}

type bridgeAuthServicePairServer struct {
	grpc.ServerStream
}

func (x *bridgeAuthServicePairServer) Send(m *BridgePairResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bridgeAuthServicePairServer) Recv() (*BridgePairRequest, error) {
	m := new(BridgePairRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BridgeAuthService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeAuthServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/woodhouse.api.BridgeAuthService/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeAuthServiceServer).Refresh(ctx, req.(*BridgeRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeAuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeAuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/woodhouse.api.BridgeAuthService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeAuthServiceServer).Logout(ctx, req.(*BridgeLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgeAuthService_ServiceDesc is the grpc.ServiceDesc for BridgeAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woodhouse.api.BridgeAuthService",
	HandlerType: (*BridgeAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Refresh",
			Handler:    _BridgeAuthService_Refresh_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _BridgeAuthService_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pair",
			Handler:       _BridgeAuthService_Pair_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bridge_service.proto",
}
