// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.2
// source: bridge_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetBridgeInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetBridgeInfoResponse) Reset() {
	*x = SetBridgeInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBridgeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBridgeInfoResponse) ProtoMessage() {}

func (x *SetBridgeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBridgeInfoResponse.ProtoReflect.Descriptor instead.
func (*SetBridgeInfoResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{0}
}

type SetDeviceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDeviceInfoResponse) Reset() {
	*x = SetDeviceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceInfoResponse) ProtoMessage() {}

func (x *SetDeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{1}
}

type SetDeviceStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDeviceStateResponse) Reset() {
	*x = SetDeviceStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeviceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceStateResponse) ProtoMessage() {}

func (x *SetDeviceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceStateResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceStateResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{2}
}

type GetDeviceRequestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BridgeId string `protobuf:"bytes,1,opt,name=bridge_id,json=bridgeId,proto3" json:"bridge_id,omitempty"`
}

func (x *GetDeviceRequestsRequest) Reset() {
	*x = GetDeviceRequestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequestsRequest) ProtoMessage() {}

func (x *GetDeviceRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequestsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceRequestsRequest) GetBridgeId() string {
	if x != nil {
		return x.BridgeId
	}
	return ""
}

var File_bridge_service_proto protoreflect.FileDescriptor

var file_bridge_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x0c, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x49, 0x64, 0x32, 0xde, 0x02, 0x0a, 0x0d, 0x42, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x42,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x77, 0x6f, 0x6f, 0x64,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x24, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x53, 0x65,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x77, 0x6f,
	0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x24, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0e,
	0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x25, 0x2e, 0x77, 0x6f, 0x6f,
	0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x1c, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6d, 0x6a, 0x69, 0x62, 0x6f, 0x6e, 0x65, 0x2f,
	0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2d, 0x34, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x6f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bridge_service_proto_rawDescOnce sync.Once
	file_bridge_service_proto_rawDescData = file_bridge_service_proto_rawDesc
)

func file_bridge_service_proto_rawDescGZIP() []byte {
	file_bridge_service_proto_rawDescOnce.Do(func() {
		file_bridge_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bridge_service_proto_rawDescData)
	})
	return file_bridge_service_proto_rawDescData
}

var file_bridge_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bridge_service_proto_goTypes = []interface{}{
	(*SetBridgeInfoResponse)(nil),    // 0: woodhouse.api.SetBridgeInfoResponse
	(*SetDeviceInfoResponse)(nil),    // 1: woodhouse.api.SetDeviceInfoResponse
	(*SetDeviceStateResponse)(nil),   // 2: woodhouse.api.SetDeviceStateResponse
	(*GetDeviceRequestsRequest)(nil), // 3: woodhouse.api.GetDeviceRequestsRequest
	(*BridgeInfo)(nil),               // 4: woodhouse.api.BridgeInfo
	(*DeviceInfo)(nil),               // 5: woodhouse.api.DeviceInfo
	(*DeviceState)(nil),              // 6: woodhouse.api.DeviceState
	(*DeviceResponse)(nil),           // 7: woodhouse.api.DeviceResponse
	(*DeviceRequest)(nil),            // 8: woodhouse.api.DeviceRequest
}
var file_bridge_service_proto_depIdxs = []int32{
	4, // 0: woodhouse.api.BridgeService.SetBridgeInfo:input_type -> woodhouse.api.BridgeInfo
	5, // 1: woodhouse.api.BridgeService.SetDeviceInfo:input_type -> woodhouse.api.DeviceInfo
	6, // 2: woodhouse.api.BridgeService.SetDeviceState:input_type -> woodhouse.api.DeviceState
	7, // 3: woodhouse.api.BridgeService.GetDeviceRequests:input_type -> woodhouse.api.DeviceResponse
	0, // 4: woodhouse.api.BridgeService.SetBridgeInfo:output_type -> woodhouse.api.SetBridgeInfoResponse
	1, // 5: woodhouse.api.BridgeService.SetDeviceInfo:output_type -> woodhouse.api.SetDeviceInfoResponse
	2, // 6: woodhouse.api.BridgeService.SetDeviceState:output_type -> woodhouse.api.SetDeviceStateResponse
	8, // 7: woodhouse.api.BridgeService.GetDeviceRequests:output_type -> woodhouse.api.DeviceRequest
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bridge_service_proto_init() }
func file_bridge_service_proto_init() {
	if File_bridge_service_proto != nil {
		return
	}
	file_bridge_proto_init()
	file_device_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bridge_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBridgeInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeviceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeviceStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceRequestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bridge_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_service_proto_goTypes,
		DependencyIndexes: file_bridge_service_proto_depIdxs,
		MessageInfos:      file_bridge_service_proto_msgTypes,
	}.Build()
	File_bridge_service_proto = out.File
	file_bridge_service_proto_rawDesc = nil
	file_bridge_service_proto_goTypes = nil
	file_bridge_service_proto_depIdxs = nil
}
