// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: bridge_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BridgeServiceClient is the client API for BridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeServiceClient interface {
	SetBridgeInfo(ctx context.Context, in *BridgeInfo, opts ...grpc.CallOption) (*SetBridgeInfoResponse, error)
	SetDeviceInfo(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*SetDeviceInfoResponse, error)
	SetDeviceState(ctx context.Context, in *DeviceState, opts ...grpc.CallOption) (*SetDeviceStateResponse, error)
	GetDeviceRequests(ctx context.Context, opts ...grpc.CallOption) (BridgeService_GetDeviceRequestsClient, error)
}

type bridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeServiceClient(cc grpc.ClientConnInterface) BridgeServiceClient {
	return &bridgeServiceClient{cc}
}

func (c *bridgeServiceClient) SetBridgeInfo(ctx context.Context, in *BridgeInfo, opts ...grpc.CallOption) (*SetBridgeInfoResponse, error) {
	out := new(SetBridgeInfoResponse)
	err := c.cc.Invoke(ctx, "/woodhouse.api.BridgeService/SetBridgeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetDeviceInfo(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*SetDeviceInfoResponse, error) {
	out := new(SetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, "/woodhouse.api.BridgeService/SetDeviceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetDeviceState(ctx context.Context, in *DeviceState, opts ...grpc.CallOption) (*SetDeviceStateResponse, error) {
	out := new(SetDeviceStateResponse)
	err := c.cc.Invoke(ctx, "/woodhouse.api.BridgeService/SetDeviceState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) GetDeviceRequests(ctx context.Context, opts ...grpc.CallOption) (BridgeService_GetDeviceRequestsClient, error) {
	stream, err := c.cc.NewStream(ctx, &BridgeService_ServiceDesc.Streams[0], "/woodhouse.api.BridgeService/GetDeviceRequests", opts...)
	if err != nil {
		return nil, err
	}
	x := &bridgeServiceGetDeviceRequestsClient{stream}
	return x, nil
}

type BridgeService_GetDeviceRequestsClient interface {
	Send(*DeviceResponse) error
	Recv() (*DeviceRequest, error)
	grpc.ClientStream
}

type bridgeServiceGetDeviceRequestsClient struct {
	grpc.ClientStream
}

func (x *bridgeServiceGetDeviceRequestsClient) Send(m *DeviceResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bridgeServiceGetDeviceRequestsClient) Recv() (*DeviceRequest, error) {
	m := new(DeviceRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BridgeServiceServer is the server API for BridgeService service.
// All implementations must embed UnimplementedBridgeServiceServer
// for forward compatibility
type BridgeServiceServer interface {
	SetBridgeInfo(context.Context, *BridgeInfo) (*SetBridgeInfoResponse, error)
	SetDeviceInfo(context.Context, *DeviceInfo) (*SetDeviceInfoResponse, error)
	SetDeviceState(context.Context, *DeviceState) (*SetDeviceStateResponse, error)
	GetDeviceRequests(BridgeService_GetDeviceRequestsServer) error
	mustEmbedUnimplementedBridgeServiceServer()
}

// UnimplementedBridgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBridgeServiceServer struct {
}

func (UnimplementedBridgeServiceServer) SetBridgeInfo(context.Context, *BridgeInfo) (*SetBridgeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBridgeInfo not implemented")
}
func (UnimplementedBridgeServiceServer) SetDeviceInfo(context.Context, *DeviceInfo) (*SetDeviceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceInfo not implemented")
}
func (UnimplementedBridgeServiceServer) SetDeviceState(context.Context, *DeviceState) (*SetDeviceStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceState not implemented")
}
func (UnimplementedBridgeServiceServer) GetDeviceRequests(BridgeService_GetDeviceRequestsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDeviceRequests not implemented")
}
func (UnimplementedBridgeServiceServer) mustEmbedUnimplementedBridgeServiceServer() {}

// UnsafeBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServiceServer will
// result in compilation errors.
type UnsafeBridgeServiceServer interface {
	mustEmbedUnimplementedBridgeServiceServer()
}

func RegisterBridgeServiceServer(s grpc.ServiceRegistrar, srv BridgeServiceServer) {
	s.RegisterService(&BridgeService_ServiceDesc, srv)
}

func _BridgeService_SetBridgeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetBridgeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/woodhouse.api.BridgeService/SetBridgeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetBridgeInfo(ctx, req.(*BridgeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/woodhouse.api.BridgeService/SetDeviceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetDeviceInfo(ctx, req.(*DeviceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/woodhouse.api.BridgeService/SetDeviceState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetDeviceState(ctx, req.(*DeviceState))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_GetDeviceRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BridgeServiceServer).GetDeviceRequests(&bridgeServiceGetDeviceRequestsServer{stream})
}

type BridgeService_GetDeviceRequestsServer interface {
	Send(*DeviceRequest) error
	Recv() (*DeviceResponse, error)
	grpc.ServerStream
}

type bridgeServiceGetDeviceRequestsServer struct {
	grpc.ServerStream
}

func (x *bridgeServiceGetDeviceRequestsServer) Send(m *DeviceRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bridgeServiceGetDeviceRequestsServer) Recv() (*DeviceResponse, error) {
	m := new(DeviceResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BridgeService_ServiceDesc is the grpc.ServiceDesc for BridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woodhouse.api.BridgeService",
	HandlerType: (*BridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBridgeInfo",
			Handler:    _BridgeService_SetBridgeInfo_Handler,
		},
		{
			MethodName: "SetDeviceInfo",
			Handler:    _BridgeService_SetDeviceInfo_Handler,
		},
		{
			MethodName: "SetDeviceState",
			Handler:    _BridgeService_SetDeviceState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDeviceRequests",
			Handler:       _BridgeService_GetDeviceRequests_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bridge_service.proto",
}

// SecBridgeServiceClient is the client API for SecBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecBridgeServiceClient interface {
	// Only available through the insecure service.
	// 1. Client sends client_id to server.
	// 2. Server sends pending response to client every second until either:
	// 2a. The user denies the pairing. - Pairing stops.
	// 2b. The client goes offline (or there is another error). - Pairing stops.
	// 2c. The user approves the pairing.
	// 3. The server starts the PAKE handshake using the key provided by the user.
	// 4. The server sends the first handshake blob to the client.
	DoPairing(ctx context.Context, opts ...grpc.CallOption) (SecBridgeService_DoPairingClient, error)
}

type secBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecBridgeServiceClient(cc grpc.ClientConnInterface) SecBridgeServiceClient {
	return &secBridgeServiceClient{cc}
}

func (c *secBridgeServiceClient) DoPairing(ctx context.Context, opts ...grpc.CallOption) (SecBridgeService_DoPairingClient, error) {
	stream, err := c.cc.NewStream(ctx, &SecBridgeService_ServiceDesc.Streams[0], "/woodhouse.api.SecBridgeService/DoPairing", opts...)
	if err != nil {
		return nil, err
	}
	x := &secBridgeServiceDoPairingClient{stream}
	return x, nil
}

type SecBridgeService_DoPairingClient interface {
	Send(*DoPairingRequest) error
	Recv() (*DoPairingResponse, error)
	grpc.ClientStream
}

type secBridgeServiceDoPairingClient struct {
	grpc.ClientStream
}

func (x *secBridgeServiceDoPairingClient) Send(m *DoPairingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *secBridgeServiceDoPairingClient) Recv() (*DoPairingResponse, error) {
	m := new(DoPairingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SecBridgeServiceServer is the server API for SecBridgeService service.
// All implementations must embed UnimplementedSecBridgeServiceServer
// for forward compatibility
type SecBridgeServiceServer interface {
	// Only available through the insecure service.
	// 1. Client sends client_id to server.
	// 2. Server sends pending response to client every second until either:
	// 2a. The user denies the pairing. - Pairing stops.
	// 2b. The client goes offline (or there is another error). - Pairing stops.
	// 2c. The user approves the pairing.
	// 3. The server starts the PAKE handshake using the key provided by the user.
	// 4. The server sends the first handshake blob to the client.
	DoPairing(SecBridgeService_DoPairingServer) error
	mustEmbedUnimplementedSecBridgeServiceServer()
}

// UnimplementedSecBridgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSecBridgeServiceServer struct {
}

func (UnimplementedSecBridgeServiceServer) DoPairing(SecBridgeService_DoPairingServer) error {
	return status.Errorf(codes.Unimplemented, "method DoPairing not implemented")
}
func (UnimplementedSecBridgeServiceServer) mustEmbedUnimplementedSecBridgeServiceServer() {}

// UnsafeSecBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecBridgeServiceServer will
// result in compilation errors.
type UnsafeSecBridgeServiceServer interface {
	mustEmbedUnimplementedSecBridgeServiceServer()
}

func RegisterSecBridgeServiceServer(s grpc.ServiceRegistrar, srv SecBridgeServiceServer) {
	s.RegisterService(&SecBridgeService_ServiceDesc, srv)
}

func _SecBridgeService_DoPairing_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SecBridgeServiceServer).DoPairing(&secBridgeServiceDoPairingServer{stream})
}

type SecBridgeService_DoPairingServer interface {
	Send(*DoPairingResponse) error
	Recv() (*DoPairingRequest, error)
	grpc.ServerStream
}

type secBridgeServiceDoPairingServer struct {
	grpc.ServerStream
}

func (x *secBridgeServiceDoPairingServer) Send(m *DoPairingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *secBridgeServiceDoPairingServer) Recv() (*DoPairingRequest, error) {
	m := new(DoPairingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SecBridgeService_ServiceDesc is the grpc.ServiceDesc for SecBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woodhouse.api.SecBridgeService",
	HandlerType: (*SecBridgeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoPairing",
			Handler:       _SecBridgeService_DoPairing_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bridge_service.proto",
}
