// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.2
// source: bridge_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BridgePairResponse_State int32

const (
	BridgePairResponse_Undefined BridgePairResponse_State = 0
	BridgePairResponse_Pending   BridgePairResponse_State = 1
	BridgePairResponse_Handshake BridgePairResponse_State = 2
)

// Enum value maps for BridgePairResponse_State.
var (
	BridgePairResponse_State_name = map[int32]string{
		0: "Undefined",
		1: "Pending",
		2: "Handshake",
	}
	BridgePairResponse_State_value = map[string]int32{
		"Undefined": 0,
		"Pending":   1,
		"Handshake": 2,
	}
)

func (x BridgePairResponse_State) Enum() *BridgePairResponse_State {
	p := new(BridgePairResponse_State)
	*p = x
	return p
}

func (x BridgePairResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BridgePairResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_service_proto_enumTypes[0].Descriptor()
}

func (BridgePairResponse_State) Type() protoreflect.EnumType {
	return &file_bridge_service_proto_enumTypes[0]
}

func (x BridgePairResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BridgePairResponse_State.Descriptor instead.
func (BridgePairResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{5, 0}
}

type SetBridgeInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetBridgeInfoResponse) Reset() {
	*x = SetBridgeInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBridgeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBridgeInfoResponse) ProtoMessage() {}

func (x *SetBridgeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBridgeInfoResponse.ProtoReflect.Descriptor instead.
func (*SetBridgeInfoResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{0}
}

type SetDeviceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDeviceInfoResponse) Reset() {
	*x = SetDeviceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceInfoResponse) ProtoMessage() {}

func (x *SetDeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{1}
}

type SetDeviceStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDeviceStateResponse) Reset() {
	*x = SetDeviceStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeviceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceStateResponse) ProtoMessage() {}

func (x *SetDeviceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceStateResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceStateResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{2}
}

type GetDeviceRequestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BridgeId string `protobuf:"bytes,1,opt,name=bridge_id,json=bridgeId,proto3" json:"bridge_id,omitempty"`
}

func (x *GetDeviceRequestsRequest) Reset() {
	*x = GetDeviceRequestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeviceRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequestsRequest) ProtoMessage() {}

func (x *GetDeviceRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequestsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceRequestsRequest) GetBridgeId() string {
	if x != nil {
		return x.BridgeId
	}
	return ""
}

type BridgePairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Only needed in the first message.
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BridgePairRequest) Reset() {
	*x = BridgePairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgePairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgePairRequest) ProtoMessage() {}

func (x *BridgePairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgePairRequest.ProtoReflect.Descriptor instead.
func (*BridgePairRequest) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{4}
}

func (x *BridgePairRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BridgePairRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BridgePairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State BridgePairResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=woodhouse.api.BridgePairResponse_State" json:"state,omitempty"`
	Data  []byte                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BridgePairResponse) Reset() {
	*x = BridgePairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgePairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgePairResponse) ProtoMessage() {}

func (x *BridgePairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgePairResponse.ProtoReflect.Descriptor instead.
func (*BridgePairResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{5}
}

func (x *BridgePairResponse) GetState() BridgePairResponse_State {
	if x != nil {
		return x.State
	}
	return BridgePairResponse_Undefined
}

func (x *BridgePairResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BridgeRefreshRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken   string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RenewThreshold uint32 `protobuf:"varint,2,opt,name=renew_threshold,json=renewThreshold,proto3" json:"renew_threshold,omitempty"` // Days remaining before expiry to cause the refresh token to be renewed. Set to zero to always renew.
}

func (x *BridgeRefreshRequest) Reset() {
	*x = BridgeRefreshRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeRefreshRequest) ProtoMessage() {}

func (x *BridgeRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeRefreshRequest.ProtoReflect.Descriptor instead.
func (*BridgeRefreshRequest) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{6}
}

func (x *BridgeRefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *BridgeRefreshRequest) GetRenewThreshold() uint32 {
	if x != nil {
		return x.RenewThreshold
	}
	return 0
}

type BridgeRefreshResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessToken  string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *BridgeRefreshResponse) Reset() {
	*x = BridgeRefreshResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeRefreshResponse) ProtoMessage() {}

func (x *BridgeRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeRefreshResponse.ProtoReflect.Descriptor instead.
func (*BridgeRefreshResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{7}
}

func (x *BridgeRefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *BridgeRefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type BridgeLogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *BridgeLogoutRequest) Reset() {
	*x = BridgeLogoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeLogoutRequest) ProtoMessage() {}

func (x *BridgeLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeLogoutRequest.ProtoReflect.Descriptor instead.
func (*BridgeLogoutRequest) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{8}
}

func (x *BridgeLogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type BridgeLogoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BridgeLogoutResponse) Reset() {
	*x = BridgeLogoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeLogoutResponse) ProtoMessage() {}

func (x *BridgeLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeLogoutResponse.ProtoReflect.Descriptor instead.
func (*BridgeLogoutResponse) Descriptor() ([]byte, []int) {
	return file_bridge_service_proto_rawDescGZIP(), []int{9}
}

var File_bridge_service_proto protoreflect.FileDescriptor

var file_bridge_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x0c, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x11, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9b, 0x01, 0x0a,
	0x12, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x27, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x48,
	0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x10, 0x02, 0x22, 0x64, 0x0a, 0x14, 0x42, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6e, 0x65, 0x77,
	0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0e, 0x72, 0x65, 0x6e, 0x65, 0x77, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64,
	0x22, 0x5f, 0x0a, 0x15, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x3a, 0x0a, 0x13, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x16, 0x0a,
	0x14, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xde, 0x02, 0x0a, 0x0d, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x42, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x24, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x53, 0x65, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x77, 0x6f, 0x6f,
	0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x24, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x53,
	0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e,
	0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x25, 0x2e, 0x77, 0x6f, 0x6f, 0x64,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x1c, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x28, 0x01, 0x30, 0x01, 0x32, 0x8d, 0x02, 0x0a, 0x11, 0x42, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x04,
	0x50, 0x61, 0x69, 0x72, 0x12, 0x20, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x54, 0x0a,
	0x07, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x23, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x22, 0x2e,
	0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6d, 0x6a, 0x69, 0x62, 0x6f, 0x6e, 0x65, 0x2f, 0x77,
	0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2d, 0x34, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x6f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bridge_service_proto_rawDescOnce sync.Once
	file_bridge_service_proto_rawDescData = file_bridge_service_proto_rawDesc
)

func file_bridge_service_proto_rawDescGZIP() []byte {
	file_bridge_service_proto_rawDescOnce.Do(func() {
		file_bridge_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bridge_service_proto_rawDescData)
	})
	return file_bridge_service_proto_rawDescData
}

var file_bridge_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bridge_service_proto_goTypes = []interface{}{
	(BridgePairResponse_State)(0),    // 0: woodhouse.api.BridgePairResponse.State
	(*SetBridgeInfoResponse)(nil),    // 1: woodhouse.api.SetBridgeInfoResponse
	(*SetDeviceInfoResponse)(nil),    // 2: woodhouse.api.SetDeviceInfoResponse
	(*SetDeviceStateResponse)(nil),   // 3: woodhouse.api.SetDeviceStateResponse
	(*GetDeviceRequestsRequest)(nil), // 4: woodhouse.api.GetDeviceRequestsRequest
	(*BridgePairRequest)(nil),        // 5: woodhouse.api.BridgePairRequest
	(*BridgePairResponse)(nil),       // 6: woodhouse.api.BridgePairResponse
	(*BridgeRefreshRequest)(nil),     // 7: woodhouse.api.BridgeRefreshRequest
	(*BridgeRefreshResponse)(nil),    // 8: woodhouse.api.BridgeRefreshResponse
	(*BridgeLogoutRequest)(nil),      // 9: woodhouse.api.BridgeLogoutRequest
	(*BridgeLogoutResponse)(nil),     // 10: woodhouse.api.BridgeLogoutResponse
	(*BridgeInfo)(nil),               // 11: woodhouse.api.BridgeInfo
	(*DeviceInfo)(nil),               // 12: woodhouse.api.DeviceInfo
	(*DeviceState)(nil),              // 13: woodhouse.api.DeviceState
	(*DeviceResponse)(nil),           // 14: woodhouse.api.DeviceResponse
	(*DeviceRequest)(nil),            // 15: woodhouse.api.DeviceRequest
}
var file_bridge_service_proto_depIdxs = []int32{
	0,  // 0: woodhouse.api.BridgePairResponse.state:type_name -> woodhouse.api.BridgePairResponse.State
	11, // 1: woodhouse.api.BridgeService.SetBridgeInfo:input_type -> woodhouse.api.BridgeInfo
	12, // 2: woodhouse.api.BridgeService.SetDeviceInfo:input_type -> woodhouse.api.DeviceInfo
	13, // 3: woodhouse.api.BridgeService.SetDeviceState:input_type -> woodhouse.api.DeviceState
	14, // 4: woodhouse.api.BridgeService.GetDeviceRequests:input_type -> woodhouse.api.DeviceResponse
	5,  // 5: woodhouse.api.BridgeAuthService.Pair:input_type -> woodhouse.api.BridgePairRequest
	7,  // 6: woodhouse.api.BridgeAuthService.Refresh:input_type -> woodhouse.api.BridgeRefreshRequest
	9,  // 7: woodhouse.api.BridgeAuthService.Logout:input_type -> woodhouse.api.BridgeLogoutRequest
	1,  // 8: woodhouse.api.BridgeService.SetBridgeInfo:output_type -> woodhouse.api.SetBridgeInfoResponse
	2,  // 9: woodhouse.api.BridgeService.SetDeviceInfo:output_type -> woodhouse.api.SetDeviceInfoResponse
	3,  // 10: woodhouse.api.BridgeService.SetDeviceState:output_type -> woodhouse.api.SetDeviceStateResponse
	15, // 11: woodhouse.api.BridgeService.GetDeviceRequests:output_type -> woodhouse.api.DeviceRequest
	6,  // 12: woodhouse.api.BridgeAuthService.Pair:output_type -> woodhouse.api.BridgePairResponse
	8,  // 13: woodhouse.api.BridgeAuthService.Refresh:output_type -> woodhouse.api.BridgeRefreshResponse
	10, // 14: woodhouse.api.BridgeAuthService.Logout:output_type -> woodhouse.api.BridgeLogoutResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_bridge_service_proto_init() }
func file_bridge_service_proto_init() {
	if File_bridge_service_proto != nil {
		return
	}
	file_bridge_proto_init()
	file_device_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bridge_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBridgeInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeviceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeviceStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeviceRequestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgePairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgePairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeRefreshRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeRefreshResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeLogoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeLogoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bridge_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bridge_service_proto_goTypes,
		DependencyIndexes: file_bridge_service_proto_depIdxs,
		EnumInfos:         file_bridge_service_proto_enumTypes,
		MessageInfos:      file_bridge_service_proto_msgTypes,
	}.Build()
	File_bridge_service_proto = out.File
	file_bridge_service_proto_rawDesc = nil
	file_bridge_service_proto_goTypes = nil
	file_bridge_service_proto_depIdxs = nil
}
