// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: device_store.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BridgeInfos  []*BridgeInfo         `protobuf:"bytes,1,rep,name=bridge_infos,json=bridgeInfos,proto3" json:"bridge_infos,omitempty"`
	DeviceInfos  []*DeviceExtendedInfo `protobuf:"bytes,2,rep,name=device_infos,json=deviceInfos,proto3" json:"device_infos,omitempty"`
	DeviceStates []*DeviceState        `protobuf:"bytes,3,rep,name=device_states,json=deviceStates,proto3" json:"device_states,omitempty"`
}

func (x *DeviceStore) Reset() {
	*x = DeviceStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStore) ProtoMessage() {}

func (x *DeviceStore) ProtoReflect() protoreflect.Message {
	mi := &file_device_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStore.ProtoReflect.Descriptor instead.
func (*DeviceStore) Descriptor() ([]byte, []int) {
	return file_device_store_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceStore) GetBridgeInfos() []*BridgeInfo {
	if x != nil {
		return x.BridgeInfos
	}
	return nil
}

func (x *DeviceStore) GetDeviceInfos() []*DeviceExtendedInfo {
	if x != nil {
		return x.DeviceInfos
	}
	return nil
}

func (x *DeviceStore) GetDeviceStates() []*DeviceState {
	if x != nil {
		return x.DeviceStates
	}
	return nil
}

var File_device_store_proto protoreflect.FileDescriptor

var file_device_store_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x1a, 0x0c, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd2, 0x01, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12,
	0x3c, 0x0a, 0x0c, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0b, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x44, 0x0a,
	0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x77, 0x6f, 0x6f, 0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x6f, 0x6f,
	0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6d, 0x6a, 0x69, 0x62, 0x6f, 0x6e, 0x65, 0x2f, 0x77, 0x6f, 0x6f,
	0x64, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2d, 0x34, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x3b,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_device_store_proto_rawDescOnce sync.Once
	file_device_store_proto_rawDescData = file_device_store_proto_rawDesc
)

func file_device_store_proto_rawDescGZIP() []byte {
	file_device_store_proto_rawDescOnce.Do(func() {
		file_device_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_store_proto_rawDescData)
	})
	return file_device_store_proto_rawDescData
}

var file_device_store_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_device_store_proto_goTypes = []interface{}{
	(*DeviceStore)(nil),        // 0: woodhouse.api.DeviceStore
	(*BridgeInfo)(nil),         // 1: woodhouse.api.BridgeInfo
	(*DeviceExtendedInfo)(nil), // 2: woodhouse.api.DeviceExtendedInfo
	(*DeviceState)(nil),        // 3: woodhouse.api.DeviceState
}
var file_device_store_proto_depIdxs = []int32{
	1, // 0: woodhouse.api.DeviceStore.bridge_infos:type_name -> woodhouse.api.BridgeInfo
	2, // 1: woodhouse.api.DeviceStore.device_infos:type_name -> woodhouse.api.DeviceExtendedInfo
	3, // 2: woodhouse.api.DeviceStore.device_states:type_name -> woodhouse.api.DeviceState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_device_store_proto_init() }
func file_device_store_proto_init() {
	if File_device_store_proto != nil {
		return
	}
	file_bridge_proto_init()
	file_device_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_device_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_device_store_proto_goTypes,
		DependencyIndexes: file_device_store_proto_depIdxs,
		MessageInfos:      file_device_store_proto_msgTypes,
	}.Build()
	File_device_store_proto = out.File
	file_device_store_proto_rawDesc = nil
	file_device_store_proto_goTypes = nil
	file_device_store_proto_depIdxs = nil
}
