package main

import (
	"context"
	"fmt"
	"os"
	"slices"
	"time"

	api "github.com/jimjibone/woodhouse-4/api/go"
	"github.com/jimjibone/woodhouse-4/log"
	"github.com/jimjibone/woodhouse-4/shared/crypt"
	"github.com/schollz/pake/v3"
	"github.com/urfave/cli/v2"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"
)

func main() {
	app := &cli.App{
		Name:                 "woodhouse-client",
		Usage:                "Runs the woodhouse client",
		EnableBashCompletion: true,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "id",
				Usage:    "client id used to register with woodhouse-core",
				Required: true,
			},
			&cli.StringFlag{
				Name:     "addr",
				Usage:    "woodhouse-core server address (disables automatic discovery)",
				Required: true,
			},
			&cli.BoolFlag{
				Name:    "debug",
				Aliases: []string{"v"},
				Usage:   "Enable debug logging",
			},
		},
		Before: func(args *cli.Context) error {
			// Setup logging.
			if args.Bool("debug") {
				log.SetOptions(log.WithMinLevel(log.DebugLevel))
			} else {
				log.SetOptions(log.WithMinLevel(log.InfoLevel))
			}
			return nil
		},
		Action: func(args *cli.Context) error {
			clientID := args.String("id")
			serverAddr := args.String("addr")

			// Connect to the server.
			log.Infof("connecting to: %s", serverAddr)

			// TODO: require valid certs
			// creds := credentials.NewTLS(&tls.Config{})
			creds := insecure.NewCredentials()
			connCtx, connCancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer connCancel()
			conn, err := grpc.DialContext(
				connCtx,
				serverAddr,
				grpc.WithTransportCredentials(creds),
			)
			if err != nil {
				return fmt.Errorf("connection failed: %w", err)
			}
			defer conn.Close()
			log.Infof("connection complete!")

			service := api.NewBridgeAuthServiceClient(conn)

			// pairCtx, pairCancel := context.WithTimeout(context.Background(), time.Second*10)
			// defer pairCancel()
			pairCtx, pairCancel := context.WithCancel(context.Background())
			defer pairCancel()
			pairingClient, err := service.Pair(pairCtx)
			if err != nil {
				return fmt.Errorf("failed to start pairing: %s", err)
			}

			// 1. Send our ID to the server.
			err = pairingClient.Send(&api.BridgePairRequest{
				ClientId: clientID,
			})
			if err != nil {
				return fmt.Errorf("failed to send client id: %s", err)
			}

			// 2. Wait for server to move on from pending.
			var res *api.BridgePairResponse
			pending := true
			for pending {
				res, err = pairingClient.Recv()
				if err != nil {
					code := status.Code(err)
					if code == codes.PermissionDenied {
						return fmt.Errorf("pairing denied")
					}
					return fmt.Errorf("failed to receive message: %s", err)
				}
				switch res.State {
				case api.BridgePairResponse_Handshake:
					log.Infof("pairing: handshake started...")
					pending = false
				case api.BridgePairResponse_Pending:
					log.Debugf("pairing: pending...")
				default:
					return fmt.Errorf("received unexpected state: %s", res.State)
				}
			}

			// Start the PAKE handshake using the key generated by us.
			log.Debugf("pairing: initialising pake")
			pakep, err := pake.InitCurve([]byte("redacted"), 1, "p521")
			if err != nil {
				return fmt.Errorf("failed to init pake: %s", err)
			}

			// 3. Receive the first PAKE handshake blob from the server.
			// NOTE: we already received the first blob in the for loop above.
			log.Debugf("pairing: received first handshake blob")
			err = pakep.Update(res.Data)
			if err != nil {
				return fmt.Errorf("failed to update handshake: %s", err)
			}

			// 4. Send the second handshake blob to the server.
			log.Debugf("pairing: sending second handshake blob")
			err = pairingClient.Send(&api.BridgePairRequest{
				Data: pakep.Bytes(),
			})
			if err != nil {
				return fmt.Errorf("failed to send handshake: %s", err)
			}

			// 5. We now have the session key. The server will now test us to
			// make sure we both have the same session key.
			log.Debugf("pairing: waiting for handshake test")
			res, err = pairingClient.Recv()
			if err != nil {
				return fmt.Errorf("failed to receive test: %s", err)
			}
			key, err := pakep.SessionKey()
			if err != nil {
				return fmt.Errorf("failed to get session key: %s", err)
			}
			decrypted, err := crypt.Decrypt(res.Data, key)
			if err != nil {
				return fmt.Errorf("failed to decrypt test: %v", err)
			}
			log.Debugf("pairing: received test")

			// 6. Reverse the bytes, then re-encrypt and send back the test.
			slices.Reverse(decrypted)
			encrypted, err := crypt.Encrypt(decrypted, key)
			if err != nil {
				return fmt.Errorf("failed to encrypt test: %v", err)
			}
			err = pairingClient.Send(&api.BridgePairRequest{
				Data: encrypted,
			})
			if err != nil {
				return fmt.Errorf("failed to send test: %s", err)
			}

			// 7. Receive the server's certificate and save it.
			res, err = pairingClient.Recv()
			if err != nil {
				return fmt.Errorf("failed to receive cert: %s", err)
			}
			decrypted, err = crypt.Decrypt(res.Data, key)
			if err != nil {
				return fmt.Errorf("failed to decrypt cert: %v", err)
			}
			log.Debugf("pairing: server cert is %s", decrypted)

			// 8. Receive our new auth tokens and save them.
			res, err = pairingClient.Recv()
			if err != nil {
				return fmt.Errorf("failed to receive token: %s", err)
			}
			decrypted, err = crypt.Decrypt(res.Data, key)
			if err != nil {
				return fmt.Errorf("failed to decrypt token: %v", err)
			}
			refreshToken := string(decrypted)
			log.Debugf("pairing: client token is %s", refreshToken)

			log.Infof("pairing complete!")

			// Now try doing a token refresh.
			// refreshCtx, refreshCancel := context.WithCancel(context.Background())
			// defer refreshCancel()
			// tokens, err := service.Refresh(refreshCtx, &api.BridgeRefreshRequest{
			// 	RefreshToken:   refreshToken,
			// 	RenewThreshold: 0,
			// })
			// if err != nil {
			// 	return fmt.Errorf("failed to refresh tokens: %v", err)
			// }
			// log.Infof("got tokens: %v", tokens)
			return nil
		},
	}

	err := app.Run(os.Args)
	if err != nil {
		log.Fatalln(err)
	}
}
