// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file clients/auth_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file clients/auth_service.proto.
 */
export const file_clients_auth_service: GenFile = /*@__PURE__*/
  fileDesc("ChpjbGllbnRzL2F1dGhfc2VydmljZS5wcm90bxIYd29vZGhvdXNlLmFwaS52MS5jbGllbnRzIi4KC1BhaXJSZXF1ZXN0EhEKCWNsaWVudF9pZBgBIAEoCRIMCgRkYXRhGAIgASgMIo0BCgxQYWlyUmVzcG9uc2USOwoFc3RhdGUYASABKA4yLC53b29kaG91c2UuYXBpLnYxLmNsaWVudHMuUGFpclJlc3BvbnNlLlN0YXRlEgwKBGRhdGEYAiABKAwiMgoFU3RhdGUSDQoJVW5kZWZpbmVkEAASCwoHUGVuZGluZxABEg0KCUhhbmRzaGFrZRACIicKDlJlZnJlc2hSZXF1ZXN0EhUKDXJlZnJlc2hfdG9rZW4YASABKAkiPgoPUmVmcmVzaFJlc3BvbnNlEhUKDXJlZnJlc2hfdG9rZW4YASABKAkSFAoMYWNjZXNzX3Rva2VuGAIgASgJIiYKDUxvZ291dFJlcXVlc3QSFQoNcmVmcmVzaF90b2tlbhgBIAEoCSIQCg5Mb2dvdXRSZXNwb25zZSINCgtQaW5nUmVxdWVzdCIOCgxQaW5nUmVzcG9uc2Uy/AIKC0F1dGhTZXJ2aWNlElkKBFBhaXISJS53b29kaG91c2UuYXBpLnYxLmNsaWVudHMuUGFpclJlcXVlc3QaJi53b29kaG91c2UuYXBpLnYxLmNsaWVudHMuUGFpclJlc3BvbnNlKAEwARJeCgdSZWZyZXNoEigud29vZGhvdXNlLmFwaS52MS5jbGllbnRzLlJlZnJlc2hSZXF1ZXN0Gikud29vZGhvdXNlLmFwaS52MS5jbGllbnRzLlJlZnJlc2hSZXNwb25zZRJbCgZMb2dvdXQSJy53b29kaG91c2UuYXBpLnYxLmNsaWVudHMuTG9nb3V0UmVxdWVzdBooLndvb2Rob3VzZS5hcGkudjEuY2xpZW50cy5Mb2dvdXRSZXNwb25zZRJVCgRQaW5nEiUud29vZGhvdXNlLmFwaS52MS5jbGllbnRzLlBpbmdSZXF1ZXN0GiYud29vZGhvdXNlLmFwaS52MS5jbGllbnRzLlBpbmdSZXNwb25zZUI9WjtnaXRodWIuY29tL2ppbWppYm9uZS93b29kaG91c2UtYXBpL2dvL3YxL2NsaWVudHM7Y2xpZW50c2FwaWIGcHJvdG8z");

/**
 * @generated from message woodhouse.api.v1.clients.PairRequest
 */
export type PairRequest = Message<"woodhouse.api.v1.clients.PairRequest"> & {
  /**
   * Only needed in the first message.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message woodhouse.api.v1.clients.PairRequest.
 * Use `create(PairRequestSchema)` to create a new message.
 */
export const PairRequestSchema: GenMessage<PairRequest> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 0);

/**
 * @generated from message woodhouse.api.v1.clients.PairResponse
 */
export type PairResponse = Message<"woodhouse.api.v1.clients.PairResponse"> & {
  /**
   * @generated from field: woodhouse.api.v1.clients.PairResponse.State state = 1;
   */
  state: PairResponse_State;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message woodhouse.api.v1.clients.PairResponse.
 * Use `create(PairResponseSchema)` to create a new message.
 */
export const PairResponseSchema: GenMessage<PairResponse> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 1);

/**
 * @generated from enum woodhouse.api.v1.clients.PairResponse.State
 */
export enum PairResponse_State {
  /**
   * @generated from enum value: Undefined = 0;
   */
  Undefined = 0,

  /**
   * @generated from enum value: Pending = 1;
   */
  Pending = 1,

  /**
   * @generated from enum value: Handshake = 2;
   */
  Handshake = 2,
}

/**
 * Describes the enum woodhouse.api.v1.clients.PairResponse.State.
 */
export const PairResponse_StateSchema: GenEnum<PairResponse_State> = /*@__PURE__*/
  enumDesc(file_clients_auth_service, 1, 0);

/**
 * @generated from message woodhouse.api.v1.clients.RefreshRequest
 */
export type RefreshRequest = Message<"woodhouse.api.v1.clients.RefreshRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message woodhouse.api.v1.clients.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export const RefreshRequestSchema: GenMessage<RefreshRequest> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 2);

/**
 * @generated from message woodhouse.api.v1.clients.RefreshResponse
 */
export type RefreshResponse = Message<"woodhouse.api.v1.clients.RefreshResponse"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;
};

/**
 * Describes the message woodhouse.api.v1.clients.RefreshResponse.
 * Use `create(RefreshResponseSchema)` to create a new message.
 */
export const RefreshResponseSchema: GenMessage<RefreshResponse> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 3);

/**
 * @generated from message woodhouse.api.v1.clients.LogoutRequest
 */
export type LogoutRequest = Message<"woodhouse.api.v1.clients.LogoutRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message woodhouse.api.v1.clients.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 4);

/**
 * @generated from message woodhouse.api.v1.clients.LogoutResponse
 */
export type LogoutResponse = Message<"woodhouse.api.v1.clients.LogoutResponse"> & {
};

/**
 * Describes the message woodhouse.api.v1.clients.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 5);

/**
 * @generated from message woodhouse.api.v1.clients.PingRequest
 */
export type PingRequest = Message<"woodhouse.api.v1.clients.PingRequest"> & {
};

/**
 * Describes the message woodhouse.api.v1.clients.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 6);

/**
 * @generated from message woodhouse.api.v1.clients.PingResponse
 */
export type PingResponse = Message<"woodhouse.api.v1.clients.PingResponse"> & {
};

/**
 * Describes the message woodhouse.api.v1.clients.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 7);

/**
 * @generated from service woodhouse.api.v1.clients.AuthService
 */
export const AuthService: GenService<{
  /**
   * Pair with (login to) the woodhouse core server. Note that this RPC can
   * wait in the pending state for a long time, until a user approves/denies
   * the pairing request. The bi-directional stream is normally used in
   * 'insecure' mode (i.e. use 'insecure skip verify' TLS option) and follows
   * this pattern:
   * 1. The client starts the bi-directional stream by sending its client_id.
   * 2. The server will send back the 'Pending' state every second until a
   *    user has either accepted or denied the pairing request.
   * 3. If the user accepts the pairing request, the server will send the
   *    first PAKE handshake blob.
   * 4. The client should read the handshake into their PAKE object and send
   *    back the second PAKE handshake blob.
   * 5. Server and client should now have the session key. The server tests
   *    this by sending some random data to client after encrypting with
   *    AES-256.
   * 6. The client should then decrypt the random bytes, reverse the order,
   *    encrypt using its session key and send it back to the server.
   * 7. If the server is happy it will send its own certificate file in PEM
   *    format which the client should save and use to verify future
   *    connections.
   * 8. The server will then generate a new refresh token (JWT) and send it to
   *    the client. The client should save this and use it to obtain new
   *    tokens using the `Refresh` RPC.
   * 9. Server and client should now both finish the RPC. The client should
   *    now call `Refresh` to obtain an access token which...
   *
   * @generated from rpc woodhouse.api.v1.clients.AuthService.Pair
   */
  pair: {
    methodKind: "bidi_streaming";
    input: typeof PairRequestSchema;
    output: typeof PairResponseSchema;
  },
  /**
   * Refresh session auth tokens. Should be called regularly before tokens
   * expire.
   *
   * @generated from rpc woodhouse.api.v1.clients.AuthService.Refresh
   */
  refresh: {
    methodKind: "unary";
    input: typeof RefreshRequestSchema;
    output: typeof RefreshResponseSchema;
  },
  /**
   * Logout the session.
   *
   * @generated from rpc woodhouse.api.v1.clients.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
  /**
   * A simple ping of the server.
   *
   * @generated from rpc woodhouse.api.v1.clients.AuthService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_clients_auth_service, 0);

