// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file clients/auth_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file clients/auth_service.proto.
 */
export const file_clients_auth_service: GenFile = /*@__PURE__*/
  fileDesc("ChpjbGllbnRzL2F1dGhfc2VydmljZS5wcm90bxIYd29vZGhvdXNlLmFwaS52MS5jbGllbnRzIqIBCgtQYWlyUmVxdWVzdBIRCgljbGllbnRfaWQYASABKAkSEwoLY2xpZW50X25hbWUYAyABKAkSGgoSY2xpZW50X2Rlc2NyaXB0aW9uGAQgASgJEhYKDmNsaWVudF92ZXJzaW9uGAUgASgJEhUKDWNsaWVudF9wdWJrZXkYBiABKAwSFAoMY2xpZW50X25vbmNlGAcgASgMSgQIAhADUgRkYXRhIusBCgxQYWlyUmVzcG9uc2USOwoFc3RhdGUYASABKA4yLC53b29kaG91c2UuYXBpLnYxLmNsaWVudHMuUGFpclJlc3BvbnNlLlN0YXRlEgwKBGRhdGEYAiABKAwSFQoNc2VydmVyX3B1YmtleRgDIAEoDBISCgpjb21taXRtZW50GAQgASgMEhQKDHNlcnZlcl9ub25jZRgFIAEoDCJPCgVTdGF0ZRINCglVbmRlZmluZWQQABILCgdQZW5kaW5nEAESDwoLS2V5RXhjaGFuZ2UQAhIKCgZSZXZlYWwQAxINCglDb25maXJtZWQQBCInCg5SZWZyZXNoUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAEgASgJIj4KD1JlZnJlc2hSZXNwb25zZRIVCg1yZWZyZXNoX3Rva2VuGAEgASgJEhQKDGFjY2Vzc190b2tlbhgCIAEoCSImCg1Mb2dvdXRSZXF1ZXN0EhUKDXJlZnJlc2hfdG9rZW4YASABKAkiEAoOTG9nb3V0UmVzcG9uc2UiDQoLUGluZ1JlcXVlc3QiDgoMUGluZ1Jlc3BvbnNlMvwCCgtBdXRoU2VydmljZRJZCgRQYWlyEiUud29vZGhvdXNlLmFwaS52MS5jbGllbnRzLlBhaXJSZXF1ZXN0GiYud29vZGhvdXNlLmFwaS52MS5jbGllbnRzLlBhaXJSZXNwb25zZSgBMAESXgoHUmVmcmVzaBIoLndvb2Rob3VzZS5hcGkudjEuY2xpZW50cy5SZWZyZXNoUmVxdWVzdBopLndvb2Rob3VzZS5hcGkudjEuY2xpZW50cy5SZWZyZXNoUmVzcG9uc2USWwoGTG9nb3V0Eicud29vZGhvdXNlLmFwaS52MS5jbGllbnRzLkxvZ291dFJlcXVlc3QaKC53b29kaG91c2UuYXBpLnYxLmNsaWVudHMuTG9nb3V0UmVzcG9uc2USVQoEUGluZxIlLndvb2Rob3VzZS5hcGkudjEuY2xpZW50cy5QaW5nUmVxdWVzdBomLndvb2Rob3VzZS5hcGkudjEuY2xpZW50cy5QaW5nUmVzcG9uc2VCPVo7Z2l0aHViLmNvbS9qaW1qaWJvbmUvd29vZGhvdXNlLWFwaS9nby92MS9jbGllbnRzO2NsaWVudHNhcGliBnByb3RvMw");

/**
 * @generated from message woodhouse.api.v1.clients.PairRequest
 */
export type PairRequest = Message<"woodhouse.api.v1.clients.PairRequest"> & {
  /**
   * Only needed in the first message.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * Only needed in the first message.
   *
   * @generated from field: string client_name = 3;
   */
  clientName: string;

  /**
   * Only needed in the first message.
   *
   * @generated from field: string client_description = 4;
   */
  clientDescription: string;

  /**
   * Only needed in the first message.
   *
   * @generated from field: string client_version = 5;
   */
  clientVersion: string;

  /**
   * Ephemeral X25519 public key PKa (first message).
   *
   * @generated from field: bytes client_pubkey = 6;
   */
  clientPubkey: Uint8Array;

  /**
   * 32-byte SAS nonce Na.
   *
   * @generated from field: bytes client_nonce = 7;
   */
  clientNonce: Uint8Array;
};

/**
 * Describes the message woodhouse.api.v1.clients.PairRequest.
 * Use `create(PairRequestSchema)` to create a new message.
 */
export const PairRequestSchema: GenMessage<PairRequest> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 0);

/**
 * @generated from message woodhouse.api.v1.clients.PairResponse
 */
export type PairResponse = Message<"woodhouse.api.v1.clients.PairResponse"> & {
  /**
   * @generated from field: woodhouse.api.v1.clients.PairResponse.State state = 1;
   */
  state: PairResponse_State;

  /**
   * Encrypted cert / refresh-token payloads.
   *
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  /**
   * Ephemeral X25519 public key PKb (KeyExchange).
   *
   * @generated from field: bytes server_pubkey = 3;
   */
  serverPubkey: Uint8Array;

  /**
   * SHA-256 commitment to server_nonce (KeyExchange).
   *
   * @generated from field: bytes commitment = 4;
   */
  commitment: Uint8Array;

  /**
   * 32-byte SAS nonce Nb, revealed (Reveal).
   *
   * @generated from field: bytes server_nonce = 5;
   */
  serverNonce: Uint8Array;
};

/**
 * Describes the message woodhouse.api.v1.clients.PairResponse.
 * Use `create(PairResponseSchema)` to create a new message.
 */
export const PairResponseSchema: GenMessage<PairResponse> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 1);

/**
 * @generated from enum woodhouse.api.v1.clients.PairResponse.State
 */
export enum PairResponse_State {
  /**
   * @generated from enum value: Undefined = 0;
   */
  Undefined = 0,

  /**
   * Keepalive while awaiting the user's confirm/deny.
   *
   * @generated from enum value: Pending = 1;
   */
  Pending = 1,

  /**
   * Carries server_pubkey and commitment.
   *
   * @generated from enum value: KeyExchange = 2;
   */
  KeyExchange = 2,

  /**
   * Carries server_nonce.
   *
   * @generated from enum value: Reveal = 3;
   */
  Reveal = 3,

  /**
   * Carries the first encrypted payload (the cert).
   *
   * @generated from enum value: Confirmed = 4;
   */
  Confirmed = 4,
}

/**
 * Describes the enum woodhouse.api.v1.clients.PairResponse.State.
 */
export const PairResponse_StateSchema: GenEnum<PairResponse_State> = /*@__PURE__*/
  enumDesc(file_clients_auth_service, 1, 0);

/**
 * @generated from message woodhouse.api.v1.clients.RefreshRequest
 */
export type RefreshRequest = Message<"woodhouse.api.v1.clients.RefreshRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message woodhouse.api.v1.clients.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export const RefreshRequestSchema: GenMessage<RefreshRequest> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 2);

/**
 * @generated from message woodhouse.api.v1.clients.RefreshResponse
 */
export type RefreshResponse = Message<"woodhouse.api.v1.clients.RefreshResponse"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;
};

/**
 * Describes the message woodhouse.api.v1.clients.RefreshResponse.
 * Use `create(RefreshResponseSchema)` to create a new message.
 */
export const RefreshResponseSchema: GenMessage<RefreshResponse> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 3);

/**
 * @generated from message woodhouse.api.v1.clients.LogoutRequest
 */
export type LogoutRequest = Message<"woodhouse.api.v1.clients.LogoutRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message woodhouse.api.v1.clients.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 4);

/**
 * @generated from message woodhouse.api.v1.clients.LogoutResponse
 */
export type LogoutResponse = Message<"woodhouse.api.v1.clients.LogoutResponse"> & {
};

/**
 * Describes the message woodhouse.api.v1.clients.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 5);

/**
 * @generated from message woodhouse.api.v1.clients.PingRequest
 */
export type PingRequest = Message<"woodhouse.api.v1.clients.PingRequest"> & {
};

/**
 * Describes the message woodhouse.api.v1.clients.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 6);

/**
 * @generated from message woodhouse.api.v1.clients.PingResponse
 */
export type PingResponse = Message<"woodhouse.api.v1.clients.PingResponse"> & {
};

/**
 * Describes the message woodhouse.api.v1.clients.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_clients_auth_service, 7);

/**
 * @generated from service woodhouse.api.v1.clients.AuthService
 */
export const AuthService: GenService<{
  /**
   * Pair with (login to) the woodhouse core server. The bi-directional stream
   * is normally used in 'insecure' mode (i.e. use 'insecure skip verify' TLS
   * option); the channel is authenticated by a commitment-based Short
   * Authentication String (SAS) that the user compares on both the client CLI
   * and the server web UI. The pattern is:
   * 1. The client starts the stream by sending its client_id and an ephemeral
   *    X25519 client_pubkey (PKa).
   * 2. The server replies with KeyExchange, carrying its ephemeral X25519
   *    server_pubkey (PKb) and a commitment to its 32-byte nonce Nb:
   *    commitment = SHA256(len‖PKb ‖ len‖PKa ‖ len‖client_id ‖ len‖Nb).
   * 3. The client sends its own 32-byte nonce Na (client_nonce).
   * 4. The server replies with Reveal, carrying server_nonce = Nb.
   * 5. The client verifies the commitment, then both sides compute the shared
   *    ECDH secret and derive, via HKDF with distinct info labels:
   *      - an 8-digit SAS (displayed on both ends for the user to compare);
   *      - a 32-byte AES-256 session key.
   * 6. The server stores the SAS on the pairing request (shown in the web UI)
   *    and sends periodic Pending keepalives while awaiting the user.
   * 7. The user compares the two 8-digit codes and clicks Confirm (or Deny).
   * 8. On confirm the server sends Confirmed with data = Encrypt(cert), then a
   *    further message with data = Encrypt(refresh token), each AES-256-GCM
   *    encrypted under the session key. On deny/timeout it returns
   *    PermissionDenied and sends nothing.
   *
   * @generated from rpc woodhouse.api.v1.clients.AuthService.Pair
   */
  pair: {
    methodKind: "bidi_streaming";
    input: typeof PairRequestSchema;
    output: typeof PairResponseSchema;
  },
  /**
   * Refresh session auth tokens. Should be called regularly before tokens
   * expire.
   *
   * @generated from rpc woodhouse.api.v1.clients.AuthService.Refresh
   */
  refresh: {
    methodKind: "unary";
    input: typeof RefreshRequestSchema;
    output: typeof RefreshResponseSchema;
  },
  /**
   * Logout the session.
   *
   * @generated from rpc woodhouse.api.v1.clients.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
  /**
   * A simple ping of the server.
   *
   * @generated from rpc woodhouse.api.v1.clients.AuthService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_clients_auth_service, 0);

