// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file clients/group.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Service_ServiceType } from "./client_service_pb";
import { file_clients_client_service } from "./client_service_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file clients/group.proto.
 */
export const file_clients_group: GenFile = /*@__PURE__*/
  fileDesc("ChNjbGllbnRzL2dyb3VwLnByb3RvEhh3b29kaG91c2UuYXBpLnYxLmNsaWVudHMiqgEKBUdyb3VwEgoKAmlkGAEgASgJEhIKCnNlcnZpY2VfaWQYAiABKAkSDAoEbmFtZRgDIAEoCRI7CgR0eXBlGAQgASgOMi0ud29vZGhvdXNlLmFwaS52MS5jbGllbnRzLlNlcnZpY2UuU2VydmljZVR5cGUSNgoHbWVtYmVycxgFIAMoCzIlLndvb2Rob3VzZS5hcGkudjEuY2xpZW50cy5Hcm91cE1lbWJlciI0CgtHcm91cE1lbWJlchIRCglkZXZpY2VfaWQYASABKAkSEgoKc2VydmljZV9pZBgCIAEoCUI9WjtnaXRodWIuY29tL2ppbWppYm9uZS93b29kaG91c2UtYXBpL2dvL3YxL2NsaWVudHM7Y2xpZW50c2FwaWIGcHJvdG8z", [file_clients_client_service]);

/**
 * @generated from message woodhouse.api.v1.clients.Group
 */
export type Group = Message<"woodhouse.api.v1.clients.Group"> & {
  /**
   * The universally unique device ID (typically a UUID or other static and unique identifier, e.g. "00158d00045c089f").
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The service ID (typically the name of the service type, e.g. "info").
   *
   * @generated from field: string service_id = 2;
   */
  serviceId: string;

  /**
   * The name of this group.
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * The service type. All members of the group must have the same service type.
   *
   * @generated from field: woodhouse.api.v1.clients.Service.ServiceType type = 4;
   */
  type: Service_ServiceType;

  /**
   * The group members.
   *
   * @generated from field: repeated woodhouse.api.v1.clients.GroupMember members = 5;
   */
  members: GroupMember[];
};

/**
 * Describes the message woodhouse.api.v1.clients.Group.
 * Use `create(GroupSchema)` to create a new message.
 */
export const GroupSchema: GenMessage<Group> = /*@__PURE__*/
  messageDesc(file_clients_group, 0);

/**
 * @generated from message woodhouse.api.v1.clients.GroupMember
 */
export type GroupMember = Message<"woodhouse.api.v1.clients.GroupMember"> & {
  /**
   * The universally unique device ID (typically a hardware address or other static and unique identifier, e.g. "00158d00045c089f").
   *
   * @generated from field: string device_id = 1;
   */
  deviceId: string;

  /**
   * The service ID (typically the name of the service type, e.g. "info").
   *
   * @generated from field: string service_id = 2;
   */
  serviceId: string;
};

/**
 * Describes the message woodhouse.api.v1.clients.GroupMember.
 * Use `create(GroupMemberSchema)` to create a new message.
 */
export const GroupMemberSchema: GenMessage<GroupMember> = /*@__PURE__*/
  messageDesc(file_clients_group, 1);

