// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file clients/auth_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LogoutRequest, LogoutResponse, PairRequest, PairResponse, PingRequest, PingResponse, RefreshRequest, RefreshResponse } from "./auth_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service woodhouse.api.v1.clients.AuthService
 */
export const AuthService = {
  typeName: "woodhouse.api.v1.clients.AuthService",
  methods: {
    /**
     * Pair with (login to) the woodhouse core server. Note that this RPC can
     * wait in the pending state for a long time, until a user approves/denies
     * the pairing request. The bi-directional stream is normally used in
     * 'insecure' mode (i.e. use 'insecure skip verify' TLS option) and follows
     * this pattern:
     * 1. The client starts the bi-directional stream by sending its client_id.
     * 2. The server will send back the 'Pending' state every second until a
     *    user has either accepted or denied the pairing request.
     * 3. If the user accepts the pairing request, the server will send the
     *    first PAKE handshake blob.
     * 4. The client should read the handshake into their PAKE object and send
     *    back the second PAKE handshake blob.
     * 5. Server and client should now have the session key. The server tests
     *    this by sending some random data to client after encrypting with
     *    AES-256.
     * 6. The client should then decrypt the random bytes, reverse the order,
     *    encrypt using its session key and send it back to the server.
     * 7. If the server is happy it will send its own certificate file in PEM
     *    format which the client should save and use to verify future
     *    connections.
     * 8. The server will then generate a new refresh token (JWT) and send it to
     *    the client. The client should save this and use it to obtain new
     *    tokens using the `Refresh` RPC.
     * 9. Server and client should now both finish the RPC. The client should
     *    now call `Refresh` to obtain an access token which...
     *
     * @generated from rpc woodhouse.api.v1.clients.AuthService.Pair
     */
    pair: {
      name: "Pair",
      I: PairRequest,
      O: PairResponse,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Refresh session auth tokens. Should be called regularly before tokens
     * expire.
     *
     * @generated from rpc woodhouse.api.v1.clients.AuthService.Refresh
     */
    refresh: {
      name: "Refresh",
      I: RefreshRequest,
      O: RefreshResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Logout the session.
     *
     * @generated from rpc woodhouse.api.v1.clients.AuthService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * A simple ping of the server.
     *
     * @generated from rpc woodhouse.api.v1.clients.AuthService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
  }
};

