// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file clients/auth_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message woodhouse.api.v1.clients.PairRequest
 */
export declare class PairRequest extends Message<PairRequest> {
  /**
   * Only needed in the first message.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  constructor(data?: PartialMessage<PairRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.PairRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PairRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PairRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PairRequest;

  static equals(a: PairRequest | PlainMessage<PairRequest> | undefined, b: PairRequest | PlainMessage<PairRequest> | undefined): boolean;
}

/**
 * @generated from message woodhouse.api.v1.clients.PairResponse
 */
export declare class PairResponse extends Message<PairResponse> {
  /**
   * @generated from field: woodhouse.api.v1.clients.PairResponse.State state = 1;
   */
  state: PairResponse_State;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  constructor(data?: PartialMessage<PairResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.PairResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PairResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PairResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PairResponse;

  static equals(a: PairResponse | PlainMessage<PairResponse> | undefined, b: PairResponse | PlainMessage<PairResponse> | undefined): boolean;
}

/**
 * @generated from enum woodhouse.api.v1.clients.PairResponse.State
 */
export declare enum PairResponse_State {
  /**
   * @generated from enum value: Undefined = 0;
   */
  Undefined = 0,

  /**
   * @generated from enum value: Pending = 1;
   */
  Pending = 1,

  /**
   * @generated from enum value: Handshake = 2;
   */
  Handshake = 2,
}

/**
 * @generated from message woodhouse.api.v1.clients.RefreshRequest
 */
export declare class RefreshRequest extends Message<RefreshRequest> {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  constructor(data?: PartialMessage<RefreshRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.RefreshRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshRequest;

  static equals(a: RefreshRequest | PlainMessage<RefreshRequest> | undefined, b: RefreshRequest | PlainMessage<RefreshRequest> | undefined): boolean;
}

/**
 * @generated from message woodhouse.api.v1.clients.RefreshResponse
 */
export declare class RefreshResponse extends Message<RefreshResponse> {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  constructor(data?: PartialMessage<RefreshResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.RefreshResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshResponse;

  static equals(a: RefreshResponse | PlainMessage<RefreshResponse> | undefined, b: RefreshResponse | PlainMessage<RefreshResponse> | undefined): boolean;
}

/**
 * @generated from message woodhouse.api.v1.clients.LogoutRequest
 */
export declare class LogoutRequest extends Message<LogoutRequest> {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  constructor(data?: PartialMessage<LogoutRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.LogoutRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutRequest;

  static equals(a: LogoutRequest | PlainMessage<LogoutRequest> | undefined, b: LogoutRequest | PlainMessage<LogoutRequest> | undefined): boolean;
}

/**
 * @generated from message woodhouse.api.v1.clients.LogoutResponse
 */
export declare class LogoutResponse extends Message<LogoutResponse> {
  constructor(data?: PartialMessage<LogoutResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.LogoutResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutResponse;

  static equals(a: LogoutResponse | PlainMessage<LogoutResponse> | undefined, b: LogoutResponse | PlainMessage<LogoutResponse> | undefined): boolean;
}

/**
 * @generated from message woodhouse.api.v1.clients.PingRequest
 */
export declare class PingRequest extends Message<PingRequest> {
  constructor(data?: PartialMessage<PingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.PingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PingRequest;

  static equals(a: PingRequest | PlainMessage<PingRequest> | undefined, b: PingRequest | PlainMessage<PingRequest> | undefined): boolean;
}

/**
 * @generated from message woodhouse.api.v1.clients.PingResponse
 */
export declare class PingResponse extends Message<PingResponse> {
  constructor(data?: PartialMessage<PingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "woodhouse.api.v1.clients.PingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PingResponse;

  static equals(a: PingResponse | PlainMessage<PingResponse> | undefined, b: PingResponse | PlainMessage<PingResponse> | undefined): boolean;
}

