// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file clients/client_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActionRequest, ActionResponse, Device, DeviceStreamRequest, Empty, ImageRequest, ImageResponse, StatusUpdate } from "./client_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service woodhouse.api.v1.clients.ClientService
 */
export declare const ClientService: {
  readonly typeName: "woodhouse.api.v1.clients.ClientService",
  readonly methods: {
    /**
     * StatusStream allows the client to stream StatusUpdates to the server. The
     * first StatusUpdate should contain the full state of the client and any
     * subsequent update should only contain diffs - i.e. include the
     * client_info and all devices. See the Device type for what to include in a
     * full state update.
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.StatusStream
     */
    readonly statusStream: {
      readonly name: "StatusStream",
      readonly I: typeof StatusUpdate,
      readonly O: typeof Empty,
      readonly kind: MethodKind.ClientStreaming,
    },
    /**
     * ActionStream allows the client to receive ActionRequests from the server
     * (when they are created by users or automations). The client must
     * eventually respond to all ActionRequests by sending an ActionResponse
     * with the same ID and the current status of the action (this allows for
     * reactive user interfaces and automations to implement retries, etc).
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.ActionStream
     */
    readonly actionStream: {
      readonly name: "ActionStream",
      readonly I: typeof ActionResponse,
      readonly O: typeof ActionRequest,
      readonly kind: MethodKind.BiDiStreaming,
    },
    /**
     * @generated from rpc woodhouse.api.v1.clients.ClientService.ImageStream
     */
    readonly imageStream: {
      readonly name: "ImageStream",
      readonly I: typeof ImageResponse,
      readonly O: typeof ImageRequest,
      readonly kind: MethodKind.BiDiStreaming,
    },
    /**
     * Get a stream of Device updates. The first batch of replies will be the
     * current state of the devices, followed by updates when they occur. The
     * stream also includes a 10 second heartbeat (an empty Device) which should
     * be ignored, but can be used to monitor the stream for disconnects.
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.DeviceStream
     */
    readonly deviceStream: {
      readonly name: "DeviceStream",
      readonly I: typeof DeviceStreamRequest,
      readonly O: typeof Device,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * Send an action to a device service.
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.SendAction
     */
    readonly sendAction: {
      readonly name: "SendAction",
      readonly I: typeof ActionRequest,
      readonly O: typeof ActionResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * Send an image request to a device service.
     *
     * @generated from rpc woodhouse.api.v1.clients.ClientService.SendImageRequest
     */
    readonly sendImageRequest: {
      readonly name: "SendImageRequest",
      readonly I: typeof ImageRequest,
      readonly O: typeof ImageResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
  }
};

