// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file clients/user_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Service } from "./client_service_pb.js";

/**
 * @generated from message woodhouse.api.v1.clients.GetDevicesRequest
 */
export const GetDevicesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "woodhouse.api.v1.clients.GetDevicesRequest",
  [],
);

/**
 * @generated from message woodhouse.api.v1.clients.DevicesStreamRequest
 */
export const DevicesStreamRequest = /*@__PURE__*/ proto3.makeMessageType(
  "woodhouse.api.v1.clients.DevicesStreamRequest",
  () => [
    { no: 1, name: "include_device_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message woodhouse.api.v1.clients.DashboardStreamRequest
 */
export const DashboardStreamRequest = /*@__PURE__*/ proto3.makeMessageType(
  "woodhouse.api.v1.clients.DashboardStreamRequest",
  [],
);

/**
 * @generated from message woodhouse.api.v1.clients.DashboardItem
 */
export const DashboardItem = /*@__PURE__*/ proto3.makeMessageType(
  "woodhouse.api.v1.clients.DashboardItem",
  () => [
    { no: 1, name: "device_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "device_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "online", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "service", kind: "message", T: Service },
  ],
);

