// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts"
// @generated from file clients/user_service.proto (package woodhouse.api.v1.clients, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DevicesStreamRequest, GetDevicesRequest } from "./user_service_pb.js";
import { ActionRequest, ActionResponse, Device, ImageRequest, ImageResponse } from "./client_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service woodhouse.api.v1.clients.UserService
 */
export const UserService = {
  typeName: "woodhouse.api.v1.clients.UserService",
  methods: {
    /**
     * @generated from rpc woodhouse.api.v1.clients.UserService.GetDevices
     */
    getDevices: {
      name: "GetDevices",
      I: GetDevicesRequest,
      O: Device,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Get a stream of Device updates. The first batch of replies will be the
     * current state of the devices, followed by updates when they occur. The
     * stream also includes a 10 second heartbeat (an empty Device) which should
     * be ignored, but can be used to monitor the stream for disconnects.
     *
     * @generated from rpc woodhouse.api.v1.clients.UserService.DevicesStream
     */
    devicesStream: {
      name: "DevicesStream",
      I: DevicesStreamRequest,
      O: Device,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Send an action to a device service.
     *
     * @generated from rpc woodhouse.api.v1.clients.UserService.SendAction
     */
    sendAction: {
      name: "SendAction",
      I: ActionRequest,
      O: ActionResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Send an image request to a device service.
     *
     * @generated from rpc woodhouse.api.v1.clients.UserService.SendImageRequest
     */
    sendImageRequest: {
      name: "SendImageRequest",
      I: ImageRequest,
      O: ImageResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
};

