# When creating/editing attribute types, make sure to update the following locations:
# - /api/v1/clients/client_service.proto (Attribute and Value messages)
# - /wh/v1/devices/attributes/*
# - /webapp2/src/routes/devices/*

# When creating/editing services, make sure to update the following locations:
# - /wh/v1/devices/services/*
# - /webapp2/src/routes/devices/*

# Device types and the services associated with them.
devices:
  - name: relay
    required_services:
      - info
      - online
      - identify
      - relay

  - name: lightbulb
    required_services:
      - info
      - online
      - identify
      - lightbulb

# Service types and the attributes associated with them.
services:
  - name: info
    description: Contains (normally) static information about a device.
    required_attributes:
      - { name: name, perms: rw, type: string, desc: "Name of the device." }
    optional_attributes:
      - { name: model,            perms: ro, type: string, desc: "Model name of this device." }
      - { name: manufacturer,     perms: ro, type: string, desc: "Manufacturer of this device." }
      - { name: serial_number,    perms: ro, type: string, desc: "Serial number of this device." }
      - { name: firmware_version, perms: ro, type: string, desc: "Firmware version running on this device." }
      - { name: web_url,          perms: ro, type: string, desc: "Device URL for direct access (eg. a device's web interface)." }

  - name: generic
    description: "Can contain any attributes."
    required_attributes:
    optional_attributes:

  - name: online
    description: "Indicates if the device is online and when it was last seen."
    required_attributes:
      - { name: online,    perms: ro, type: bool }
      - { name: last_seen, perms: ro, type: time }

  - name: battery
    description: "Indicates the battery level of a device."
    required_attributes:
      - { name: level, perms: ro, type: int, min: 0, max: 100, step: 1, unit: percentage }

  - name: update
    description: Device update information and control.
    required_attributes:
      - { name: available, perms: ro, type: bool }
    optional_attributes:
      - { name: current_version, perms: ro, type: string }
      - { name: update_version, perms: ro, type: string }
      - { name: start_update, perms: wo, type: bool }
      - { name: updating, perms: ro, type: bool }
      - { name: progress, perms: ro, type: int, min: 0, max: 100, step: 1, unit: percentage }
      - { name: remaining, perms: ro, type: duration, min: 0, max: 3600, step: 1, unit: seconds }

  - name: identify
    description: Allows a device to make itself identifyable (typically flashing a light).
    required_attributes:
      - { name: identify, perms: rw, type: bool }

  - name: input
    description: A binary signal which could represent a button press/toggle.
    required_attributes:
      - { name: on, perms: ro, type: bool }

  - name: contact
    description: A binary signal which represents that a contact sensor is closed (e.g. a door or window).
    required_attributes:
      - { name: contact, perms: ro, type: bool }

  - name: relay
    description: A controllable relay with optional power monitoring.
    required_attributes:
      - { name: on, perms: rw, type: bool }
    optional_attributes:
      - { name: voltage,     perms: ro, type: float, unit: volts }
      - { name: current,     perms: ro, type: float, unit: amps }
      - { name: power,       perms: ro, type: float, unit: watts }
      - { name: temperature, perms: ro, type: float, unit: celsius } # TODO: break out into "device_temperature" service?

  - name: dimmer
    description: A controllable dimmer.
    required_attributes:
      - { name: on,         perms: rw, type: bool }
      - { name: brightness, perms: rw, type: int, min: 0, max: 100, step: 1, unit: percentage }

  - name: power_monitor
    description: Power monitoring.
    optional_attributes:
      - { name: voltage,     perms: ro, type: float, unit: volts }
      - { name: current,     perms: ro, type: float, unit: amps }
      - { name: power,       perms: ro, type: float, unit: watts }
      - { name: temperature, perms: ro, type: float, unit: celsius } # TODO: break out into "device_temperature" service?

  - name: device_temp
    description: Allows a device to self report its temperature.
    required_attributes:
      - { name: temperature, perms: ro, type: float, unit: celsius }

  - name: lightbulb
    description: A light/lightbulb with optional brightness and color control.
    required_attributes:
      - { name: on, perms: rw, type: bool }
    optional_attributes:
      - { name: brightness,    perms: rw, type: int,      min: 0, max: 100, step: 1, unit: percentage }
      - { name: saturation,    perms: rw, type: int,      min: 0, max: 100, step: 1, unit: percentage }
      - { name: hue,           perms: rw, type: float,    min: 0, max: 360, step: 1, unit: arc degrees }
      - { name: color_temp,    perms: rw, type: float,    min: 0, max: 360, step: 1, unit: mireds }
      - { name: transition,    perms: wo, type: duration, min: 0, max: 300, step: 1, unit: seconds }
      - { name: color,         perms: rw, type: color }

  - name: climate
    description: A climate control device providing heating and possibly cooling to an area.
    required_attributes:
      - { name: heating_setpoint, perms: rw, type: float, min: 5, max: 30, step: 0.5, unit: celsius }
      - { name: local_temperature, perms: ro, type: float, unit: celsius }
    optional_attributes:
      - { name: cooling_setpoint, perms: rw, type: float, min: 5, max: 30, step: 0.5, unit: celsius }
      - { name: pi_heating_demand, perms: ro, type: int, min: 0, max: 100, step: 1, unit: percentage }
      - { name: heating_demand, perms: ro, type: bool }

  - name: cover
    description: A cover control device, such as a motor to control the position of a window blind.
    required_attributes:
      - { name: position, perms: rw, type: int, min: 0, max: 100, step: 1, unit: percentage }
      - { name: state,    perms: rw, type: enum }

  - name: button
    description: A button which can report various states. Sometimes reports states of multiple buttons.
    required_attributes:
      - { name: state, perms: ro, type: enum }

  - name: environment
    description: A sensor monitoring conditions of the local environment.
    optional_attributes:
      - { name: temperature, perms: ro, type: float, unit: celsius }
      - { name: humidity, perms: ro, type: float, unit: '%' }
      - { name: pressure, perms: ro, type: float, unit: '%' }

  - name: camera
    required_attributes:
      - { name: motion, perms: ro, type: bool }
      - { name: detection, perms: ro, type: bool }
      - { name: detection_type, perms: ro, type: enum }
      - { name: detection_type, perms: ro, type: enum }

  - name: motion
    description: A sensor which detects motion, typically via PIR.
    required_attributes:
      - { name: motion, perms: ro, type: bool }

  - name: presence
    description: A sensor which detects the presence of objects.
    required_attributes:
      - { name: motion,   perms: ro, type: bool, desc: 'Motion was detected recently.' }
      - { name: presence, perms: ro, type: bool, desc: 'Something is within the detection area (may not be moving).' }
      - { name: distance, perms: ro, type: float, unit: meters, desc: 'The distance to the detected target.' }

# Attribute types
attributes:
  - name: boolean
  - name: int
  - name: float
  - name: text
  - name: duration
  - name: time
  - name: color_mode
  - name: color
    values:
      # Color expressed in the CIE 1931 color space (x/y)
      - x: float
      - y: float
      # Color expressed as hue/saturation
      - hue: float
      - sat: float
