version: '3'

tasks:
  default:
    deps:
      - proto

  get-protoc-gen-ts:
    run: when_changed
    status:
      - test -f node_modules/.bin/protoc-gen-ts{{exeExt}}
    cmds:
      - npm install

  get-protoc-gen-grpc-web:
    run: when_changed
    status:
      - test -f .bin/protoc-gen-grpc-web{{exeExt}}
    vars:
      VERSION: "1.4.2"
    cmds:
      - mkdir -p .bin
      - wget -O .bin/grpc-web.tar.gz https://github.com/grpc/grpc-web/archive/refs/tags/{{.VERSION}}.tar.gz
      - cd .bin && tar xzf grpc-web.tar.gz
      - cd .bin/grpc-web-{{.VERSION}} && CPPFLAGS="$(pkg-config --cflags-only-I protobuf)" LDFLAGS="$(pkg-config --libs-only-L protobuf)" make plugin
      - cp .bin/grpc-web-{{.VERSION}}/javascript/net/grpc/web/generator/protoc-gen-grpc-web{{exeExt}} .bin/protoc-gen-grpc-web{{exeExt}}
      - rm -r .bin/grpc-web.tar.gz .bin/grpc-web-{{.VERSION}}

  # get-protoc-gen-grpc-web:
  #   run: when_changed
  #   status:
  #     - test -f .bin/protoc-gen-grpc-web{{exeExt}}
  #   cmds:
  #     - mkdir -p .bin
  #     - wget -O .bin/protoc-gen-grpc-web{{exeExt}} https://github.com/grpc/grpc-web/releases/download/1.4.0/protoc-gen-grpc-web-1.4.2-{{OS}}-{{ARCH | replace "arm64" "aarch64"}}
  #     - chmod +x .bin/protoc-gen-grpc-web{{exeExt}}

  proto:
    run: when_changed
    deps:
      - get-protoc-gen-ts
      - get-protoc-gen-grpc-web
    sources:
      - ../api/*.proto
    generates:
      - ./go/*.pb.go
    vars:
      PROTOC_GEN_TS: node_modules/.bin/protoc-gen-ts{{exeExt}}
      PROTOC_GEN_GRPC_WEB: .bin/protoc-gen-grpc-web{{exeExt}}
    cmds:
      - mkdir -p ./src/api
      - protoc -I../api --plugin="protoc-gen-ts={{.PROTOC_GEN_TS}}" --js_out=import_style=commonjs:./src/api --ts_out=./src/api ../api/*.proto
      - protoc -I../api --plugin="{{.PROTOC_GEN_GRPC_WEB}}" --grpc-web_out=import_style=typescript,mode=grpcwebtext:./src/api ../api/*_service.proto
